# Generated by Django 5.2.16 on 2026-07-27 21:47

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("manage_users", "Pode criar e manter usuários"),
                    ("manage_roles", "Pode criar e manter papéis e permissões"),
                    (
                        "link_ad_identity",
                        "Pode vincular e desvincular identidades do AD",
                    ),
                    ("view_account_audit", "Pode consultar a auditoria de contas"),
                    ("query_senior_references", "Pode consultar referências do Senior"),
                ],
                "verbose_name": "usuário",
                "verbose_name_plural": "usuários",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="ad_linked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ad_links_performed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="vinculado ao AD por",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(
                default=False, verbose_name="deve alterar a senha no próximo acesso"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="version",
            field=models.PositiveIntegerField(default=1, verbose_name="versão de concorrência"),
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="código"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nome")),
                ("description", models.TextField(blank=True, verbose_name="descrição")),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="versão de concorrência"),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="sgpd_roles",
                        to="auth.permission",
                        verbose_name="permissões",
                    ),
                ),
            ],
            options={
                "verbose_name": "papel",
                "verbose_name_plural": "papéis",
                "db_table": "SGPD_ROLE",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="AccountAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("USER_CREATED", "Usuário criado"),
                            ("USER_UPDATED", "Usuário atualizado"),
                            ("USER_ACTIVATED", "Usuário ativado"),
                            ("USER_DEACTIVATED", "Usuário desativado"),
                            ("PASSWORD_CHANGED", "Senha alterada pelo usuário"),
                            ("PASSWORD_RESET", "Senha redefinida"),
                            ("ROLE_CREATED", "Papel criado"),
                            ("ROLE_UPDATED", "Papel atualizado"),
                            ("ROLE_ASSIGNED", "Papel atribuído"),
                            ("ROLE_REVOKED", "Papel revogado"),
                            ("AD_LINKED", "Identidade AD vinculada"),
                            ("AD_UNLINKED", "Identidade AD desvinculada"),
                        ],
                        max_length=30,
                        verbose_name="tipo do evento",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(max_length=30, verbose_name="tipo da entidade"),
                ),
                (
                    "entity_id",
                    models.CharField(max_length=64, verbose_name="identificador da entidade"),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ocorrido em"),
                ),
                ("reason", models.TextField(verbose_name="justificativa")),
                ("changes", models.JSONField(default=dict, verbose_name="alterações")),
                (
                    "correlation_id",
                    models.CharField(default="-", max_length=64, verbose_name="correlation ID"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="account_events_performed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ator",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="account_audit_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário afetado",
                    ),
                ),
            ],
            options={
                "verbose_name": "evento de auditoria de conta",
                "verbose_name_plural": "eventos de auditoria de contas",
                "db_table": "SGPD_ACCOUNT_AUDIT",
                "ordering": ("-occurred_at", "-id"),
                "indexes": [
                    models.Index(fields=["target_user", "occurred_at"], name="SGPD_IX_AUDIT_USER"),
                    models.Index(fields=["correlation_id"], name="SGPD_IX_AUDIT_CORR"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("GLOBAL", "Global"),
                            ("COMPANY", "Empresa"),
                            ("BRANCH", "Filial"),
                        ],
                        default="GLOBAL",
                        max_length=10,
                        verbose_name="tipo de escopo",
                    ),
                ),
                (
                    "company_code",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="código da empresa"
                    ),
                ),
                (
                    "branch_code",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="código da filial"
                    ),
                ),
                (
                    "scope_key",
                    models.CharField(editable=False, max_length=64, verbose_name="chave do escopo"),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="válido desde"
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(blank=True, null=True, verbose_name="válido até"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="atribuído em"),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="revogado em"),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_assignments_performed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="atribuído por",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_revocations_performed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="revogado por",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="accounts.role",
                        verbose_name="papel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "atribuição de papel",
                "verbose_name_plural": "atribuições de papéis",
                "db_table": "SGPD_ROLE_ASSIGN",
                "ordering": ("user_id", "role__code", "scope_key"),
                "indexes": [
                    models.Index(
                        fields=["user", "is_active", "valid_from"],
                        name="SGPD_IX_ROLE_USER",
                    ),
                    models.Index(
                        fields=["company_code", "branch_code", "is_active"],
                        name="SGPD_IX_ROLE_ORG",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "role", "scope_key"), name="SGPD_UQ_ROLE_SCOPE"
                    )
                ],
            },
        ),
    ]
