# Generated by Django 5.2.16 on 2026-07-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_options_user_ad_linked_by_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="roleassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("branch_code__isnull", True),
                        ("company_code__isnull", True),
                        ("scope_type", "GLOBAL"),
                    ),
                    models.Q(
                        ("branch_code__isnull", True),
                        ("company_code__isnull", False),
                        ("scope_type", "COMPANY"),
                    ),
                    models.Q(
                        ("branch_code__isnull", False),
                        ("company_code__isnull", False),
                        ("scope_type", "BRANCH"),
                    ),
                    _connector="OR",
                ),
                name="SGPD_CK_ROLE_SCOPE",
            ),
        ),
        migrations.AddConstraint(
            model_name="roleassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_until__isnull", True),
                    ("valid_until__gt", models.F("valid_from")),
                    _connector="OR",
                ),
                name="SGPD_CK_ROLE_VALID",
            ),
        ),
        migrations.AddConstraint(
            model_name="roleassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_active", True),
                        ("revoked_at__isnull", True),
                        ("revoked_by__isnull", True),
                    ),
                    models.Q(
                        ("is_active", False),
                        ("revoked_at__isnull", False),
                        ("revoked_by__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="SGPD_CK_ROLE_REVOKE",
            ),
        ),
    ]
