# Generated by Django 5.2.16 on 2026-07-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_roleassignment_sgpd_ck_role_scope_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login realizado"),
                    ("LOGOUT", "Logout realizado"),
                    ("LOGIN_FAILED", "Falha de autenticação"),
                    ("USER_CREATED", "Usuário criado"),
                    ("USER_UPDATED", "Usuário atualizado"),
                    ("USER_ACTIVATED", "Usuário ativado"),
                    ("USER_DEACTIVATED", "Usuário desativado"),
                    ("PASSWORD_CHANGED", "Senha alterada pelo usuário"),
                    ("PASSWORD_RESET", "Senha redefinida"),
                    ("ROLE_CREATED", "Papel criado"),
                    ("ROLE_UPDATED", "Papel atualizado"),
                    ("ROLE_ASSIGNED", "Papel atribuído"),
                    ("ROLE_REVOKED", "Papel revogado"),
                    ("AD_LINKED", "Identidade AD vinculada"),
                    ("AD_UNLINKED", "Identidade AD desvinculada"),
                ],
                max_length=30,
                verbose_name="tipo do evento",
            ),
        ),
    ]
