# Generated by Django 5.2.16 on 2026-07-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_accountauditevent_event_type"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="accountauditevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("correlation_id__isnull", False),
                    ("entity_id__isnull", False),
                    ("entity_type__isnull", False),
                    ("event_type__isnull", False),
                    ("reason__isnull", False),
                ),
                name="SGPD_CK_AUDIT_REQUIRED",
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.CheckConstraint(
                condition=models.Q(("code__isnull", False), ("name__isnull", False)),
                name="SGPD_CK_ROLE_REQUIRED",
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gt", 0)), name="SGPD_CK_ROLE_VERSION"
            ),
        ),
        migrations.AddConstraint(
            model_name="roleassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(("scope_key__isnull", False), ("scope_type__isnull", False)),
                name="SGPD_CK_ASSIGN_REQUIRED",
            ),
        ),
        migrations.AddConstraint(
            model_name="roleassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("company_code__isnull", True),
                        ("company_code__gt", 0),
                        _connector="OR",
                    ),
                    models.Q(
                        ("branch_code__isnull", True),
                        ("branch_code__gt", 0),
                        _connector="OR",
                    ),
                ),
                name="SGPD_CK_ROLE_CODES",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("email__isnull", False),
                    ("first_name__isnull", False),
                    ("last_name__isnull", False),
                    ("password__isnull", False),
                    ("username__isnull", False),
                ),
                name="SGPD_CK_USER_REQUIRED",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("ad_identifier__isnull", True),
                        ("ad_linked_at__isnull", True),
                        ("ad_linked_by__isnull", True),
                        ("ad_username__isnull", True),
                    ),
                    models.Q(
                        ("ad_identifier__isnull", False),
                        ("ad_linked_at__isnull", False),
                        ("ad_linked_by__isnull", False),
                        ("ad_username__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="SGPD_CK_USER_AD_LINK",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gt", 0)), name="SGPD_CK_USER_VERSION"
            ),
        ),
    ]
