# Generated by Django 5.2.16 on 2026-07-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_fixed_responsible_sector_role"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="role",
            name="SGPD_CK_ROLE_ACTIVE_CODE",
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(code__in=("DP", "RESPONSAVEL_SETOR")) | models.Q(is_active=False)
                ),
                name="SGPD_CK_ROLE_ACTIVE_CODE",
            ),
        ),
    ]
