# Generated by Django 5.2.16 on 2026-07-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_derive_sector_responsible_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login realizado"),
                    ("LOGOUT", "Logout realizado"),
                    ("LOGIN_FAILED", "Falha de autenticação"),
                    ("USER_CREATED", "Usuário criado"),
                    ("USER_UPDATED", "Usuário atualizado"),
                    ("USER_ACTIVATED", "Usuário ativado"),
                    ("USER_DEACTIVATED", "Usuário desativado"),
                    ("PASSWORD_CHANGED", "Senha alterada pelo usuário"),
                    ("PASSWORD_RESET", "Senha redefinida"),
                    ("ROLE_CREATED", "Papel criado"),
                    ("ROLE_UPDATED", "Papel atualizado"),
                    ("ROLE_ASSIGNED", "Papel atribuído"),
                    ("ROLE_REVOKED", "Papel revogado"),
                    ("AD_LINKED", "Identidade AD vinculada"),
                    ("AD_UNLINKED", "Identidade AD desvinculada"),
                    ("LDAP_CONFIG_UPDATED", "Configuração LDAP atualizada"),
                    ("LDAP_CERT_UPLOADED", "Certificado LDAP enviado"),
                    ("LDAP_CONNECTION_TESTED", "Conexão LDAP testada"),
                    ("EMAIL_CONFIG_UPDATED", "Configuração de e-mail atualizada"),
                    ("EMAIL_TEST_SENT", "Mensagem de prova de e-mail enviada"),
                ],
                max_length=30,
                verbose_name="tipo do evento",
            ),
        ),
    ]
