# Generated by Django 5.2.16 on 2026-08-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_alter_accountauditevent_event_type"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="role",
            name="SGPD_CK_ROLE_ACTIVE_CODE",
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "code__in",
                        (
                            "DP",
                            "DP_GERENTE",
                            "GRUPOS_TEMPLATE_ADMIN",
                            "SETORES_ADMIN",
                            "USUARIOS_ADMIN",
                        ),
                    ),
                    ("is_active", False),
                    _connector="OR",
                ),
                name="SGPD_CK_ROLE_ACTIVE_CODE",
            ),
        ),
    ]
