# Generated by Django 5.2.16 on 2026-07-29 12:57

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OffboardingProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("RASCUNHO", "Rascunho")],
                        default="RASCUNHO",
                        max_length=30,
                        verbose_name="situação",
                    ),
                ),
                (
                    "company_code",
                    models.PositiveIntegerField(verbose_name="código da empresa"),
                ),
                (
                    "branch_code",
                    models.PositiveIntegerField(verbose_name="código da filial"),
                ),
                (
                    "employee_type_code",
                    models.PositiveIntegerField(verbose_name="tipo de colaborador"),
                ),
                (
                    "employee_registration",
                    models.PositiveIntegerField(verbose_name="matrícula"),
                ),
                (
                    "active_employee_key",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="chave do processo ativo",
                    ),
                ),
                (
                    "manager_name_snapshot",
                    models.CharField(max_length=301, verbose_name="nome histórico do gestor"),
                ),
                (
                    "manager_email_snapshot",
                    models.EmailField(max_length=254, verbose_name="e-mail histórico do gestor"),
                ),
                (
                    "opened_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="aberto em"),
                ),
                (
                    "planned_termination_date",
                    models.DateField(verbose_name="data prevista de desligamento"),
                ),
                ("due_date", models.DateField(verbose_name="data limite")),
                ("reason", models.TextField(verbose_name="motivo")),
                (
                    "priority",
                    models.CharField(max_length=50, verbose_name="prioridade"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="observações")),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="versão de concorrência"),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_offboarding_processes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="gestor imediato",
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opened_offboarding_processes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="aberto por",
                    ),
                ),
            ],
            options={
                "verbose_name": "processo demissional",
                "verbose_name_plural": "processos demissionais",
                "db_table": "SGPD_OFFBOARDING_PROCESS",
                "ordering": ("-opened_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="EmployeeSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_code",
                    models.PositiveIntegerField(verbose_name="código da empresa"),
                ),
                (
                    "branch_code",
                    models.PositiveIntegerField(verbose_name="código da filial"),
                ),
                (
                    "branch_legal_name",
                    models.CharField(max_length=255, verbose_name="razão social da filial"),
                ),
                (
                    "employee_type_code",
                    models.PositiveIntegerField(verbose_name="tipo de colaborador"),
                ),
                (
                    "employee_type_description",
                    models.CharField(
                        max_length=255, verbose_name="descrição do tipo de colaborador"
                    ),
                ),
                ("registration", models.PositiveIntegerField(verbose_name="matrícula")),
                (
                    "employee_name",
                    models.CharField(max_length=255, verbose_name="nome do colaborador"),
                ),
                (
                    "masked_cpf",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="CPF mascarado",
                    ),
                ),
                ("admission_date", models.DateField(verbose_name="data de admissão")),
                (
                    "leave_code",
                    models.PositiveIntegerField(verbose_name="código da situação"),
                ),
                (
                    "leave_description",
                    models.CharField(max_length=255, verbose_name="descrição da situação"),
                ),
                (
                    "leave_date",
                    models.DateField(blank=True, null=True, verbose_name="data de afastamento"),
                ),
                (
                    "job_structure_code",
                    models.PositiveIntegerField(verbose_name="estrutura de cargos"),
                ),
                (
                    "job_code",
                    models.CharField(max_length=50, verbose_name="código do cargo"),
                ),
                (
                    "job_description",
                    models.CharField(max_length=255, verbose_name="descrição do cargo"),
                ),
                (
                    "cost_center_code",
                    models.CharField(max_length=50, verbose_name="código do centro de custo"),
                ),
                (
                    "cost_center_description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="descrição do centro de custo",
                    ),
                ),
                (
                    "source_updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="origem atualizada em"
                    ),
                ),
                (
                    "source_queried_at",
                    models.DateTimeField(verbose_name="origem consultada em"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "process",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_snapshot",
                        to="offboarding.offboardingprocess",
                        verbose_name="processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "snapshot do colaborador",
                "verbose_name_plural": "snapshots dos colaboradores",
                "db_table": "SGPD_EMPLOYEE_SNAPSHOT",
            },
        ),
        migrations.CreateModel(
            name="ProcessAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("PROCESS_OPENED", "Processo aberto")],
                        max_length=30,
                        verbose_name="tipo do evento",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ocorrido em"),
                ),
                ("description", models.TextField(verbose_name="descrição")),
                ("data", models.JSONField(default=dict, verbose_name="dados")),
                (
                    "correlation_id",
                    models.CharField(default="-", max_length=64, verbose_name="correlation ID"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offboarding_events_performed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ator",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="offboarding.offboardingprocess",
                        verbose_name="processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "evento de processo",
                "verbose_name_plural": "eventos de processos",
                "db_table": "SGPD_PROCESS_AUDIT",
                "ordering": ("-occurred_at", "-id"),
            },
        ),
        migrations.AddIndex(
            model_name="offboardingprocess",
            index=models.Index(fields=["status", "due_date"], name="SGPD_IX_PROCESS_STATUS_DUE"),
        ),
        migrations.AddIndex(
            model_name="offboardingprocess",
            index=models.Index(
                fields=[
                    "company_code",
                    "branch_code",
                    "employee_type_code",
                    "employee_registration",
                    "opened_at",
                ],
                name="SGPD_IX_PROCESS_EMP_OPEN",
            ),
        ),
        migrations.AddIndex(
            model_name="offboardingprocess",
            index=models.Index(fields=["opened_by", "opened_at"], name="SGPD_IX_PROCESS_OPENED_BY"),
        ),
        migrations.AddConstraint(
            model_name="offboardingprocess",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("branch_code__gt", 0),
                    ("company_code__gt", 0),
                    ("due_date__isnull", False),
                    ("employee_registration__gt", 0),
                    ("employee_type_code__gt", 0),
                    ("manager__isnull", False),
                    ("manager_email_snapshot__isnull", False),
                    ("manager_name_snapshot__isnull", False),
                    ("opened_by__isnull", False),
                    ("planned_termination_date__isnull", False),
                    ("priority__isnull", False),
                    ("reason__isnull", False),
                    ("status__isnull", False),
                ),
                name="SGPD_CK_PROCESS_REQUIRED",
            ),
        ),
        migrations.AddConstraint(
            model_name="offboardingprocess",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gt", 0)), name="SGPD_CK_PROCESS_VERSION"
            ),
        ),
        migrations.AddConstraint(
            model_name="employeesnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("admission_date__isnull", False),
                    ("branch_code__gt", 0),
                    ("branch_legal_name__isnull", False),
                    ("company_code__gt", 0),
                    ("cost_center_code__isnull", False),
                    ("employee_name__isnull", False),
                    ("employee_type_code__gt", 0),
                    ("employee_type_description__isnull", False),
                    ("job_code__isnull", False),
                    ("job_description__isnull", False),
                    ("job_structure_code__gt", 0),
                    ("leave_code__gt", 0),
                    ("leave_description__isnull", False),
                    ("process__isnull", False),
                    ("registration__gt", 0),
                    ("source_queried_at__isnull", False),
                ),
                name="SGPD_CK_SNAPSHOT_REQUIRED",
            ),
        ),
        migrations.AddIndex(
            model_name="processauditevent",
            index=models.Index(
                fields=["process", "occurred_at"], name="SGPD_IX_PROCESS_AUDIT_PROC"
            ),
        ),
        migrations.AddIndex(
            model_name="processauditevent",
            index=models.Index(fields=["correlation_id"], name="SGPD_IX_PROCESS_AUDIT_CORR"),
        ),
        migrations.AddConstraint(
            model_name="processauditevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("actor__isnull", False),
                    ("correlation_id__isnull", False),
                    ("description__isnull", False),
                    ("event_type__isnull", False),
                    ("process__isnull", False),
                ),
                name="SGPD_CK_PROCESS_AUDIT_REQ",
            ),
        ),
    ]
