# Generated by Django 5.2.16 on 2026-07-29 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offboarding", "0001_initial"),
        ("sectors", "0003_responsibility_inherits_sector_scope"),
        ("templates_engine", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessActionIdempotency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=30, verbose_name="ação")),
                (
                    "idempotency_key",
                    models.CharField(max_length=100, verbose_name="chave de idempotência"),
                ),
                (
                    "request_hash",
                    models.CharField(max_length=64, verbose_name="hash da requisição"),
                ),
                ("response", models.JSONField(default=dict, verbose_name="resposta")),
                (
                    "completed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="concluída em"),
                ),
            ],
            options={
                "verbose_name": "registro de idempotência do processo",
                "verbose_name_plural": "registros de idempotência dos processos",
                "db_table": "SGPD_PROCESS_IDEMPOTENCY",
                "ordering": ("-completed_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ProcessChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_snapshot",
                    models.CharField(max_length=50, verbose_name="código histórico"),
                ),
                (
                    "question_snapshot",
                    models.TextField(verbose_name="pergunta histórica"),
                ),
                (
                    "response_type_snapshot",
                    models.CharField(max_length=20, verbose_name="tipo histórico de resposta"),
                ),
                ("is_required", models.BooleanField(verbose_name="obrigatório")),
                (
                    "blocks_process",
                    models.BooleanField(verbose_name="bloqueia o processo"),
                ),
                (
                    "requires_evidence",
                    models.BooleanField(verbose_name="exige evidência"),
                ),
                (
                    "allows_pending",
                    models.BooleanField(verbose_name="permite pendência"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(verbose_name="ordem de exibição"),
                ),
                (
                    "config_snapshot",
                    models.JSONField(default=dict, verbose_name="configuração histórica"),
                ),
                (
                    "response",
                    models.JSONField(blank=True, null=True, verbose_name="resposta"),
                ),
                (
                    "answered_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="respondido em"),
                ),
            ],
            options={
                "verbose_name": "item de checklist do processo",
                "verbose_name_plural": "itens de checklist dos processos",
                "db_table": "SGPD_PROCESS_CHECKLIST_ITEM",
                "ordering": ("task_id", "display_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProcessSectorOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("INCLUDE", "Incluir"), ("EXCLUDE", "Remover")],
                        max_length=10,
                        verbose_name="ação",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="obrigatório"),
                ),
                (
                    "blocks_process",
                    models.BooleanField(default=True, verbose_name="bloqueia o processo"),
                ),
                (
                    "due_hours_override",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="prazo específico em horas"
                    ),
                ),
                ("reason", models.TextField(verbose_name="justificativa")),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="alterado em"),
                ),
            ],
            options={
                "verbose_name": "ajuste manual de setor",
                "verbose_name_plural": "ajustes manuais de setores",
                "db_table": "SGPD_PROCESS_SECTOR_OVERRIDE",
                "ordering": ("process_id", "sector_id"),
            },
        ),
        migrations.CreateModel(
            name="ProcessSectorTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDENTE", "Pendente")],
                        default="PENDENTE",
                        max_length=30,
                        verbose_name="situação",
                    ),
                ),
                ("is_required", models.BooleanField(verbose_name="obrigatório")),
                (
                    "blocks_process",
                    models.BooleanField(verbose_name="bloqueia o processo"),
                ),
                (
                    "sector_code_snapshot",
                    models.CharField(max_length=50, verbose_name="código histórico do setor"),
                ),
                (
                    "sector_name_snapshot",
                    models.CharField(max_length=120, verbose_name="nome histórico do setor"),
                ),
                (
                    "template_code_snapshot",
                    models.CharField(max_length=50, verbose_name="código histórico do template"),
                ),
                (
                    "template_version_snapshot",
                    models.PositiveIntegerField(verbose_name="versão histórica do template"),
                ),
                (
                    "sla_hours_snapshot",
                    models.PositiveIntegerField(verbose_name="SLA histórico em horas"),
                ),
                ("due_at", models.DateTimeField(verbose_name="data limite")),
                ("started_at", models.DateTimeField(verbose_name="iniciada em")),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="concluída em"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="observações")),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="versão de concorrência"),
                ),
            ],
            options={
                "verbose_name": "tarefa de setor",
                "verbose_name_plural": "tarefas de setores",
                "db_table": "SGPD_PROCESS_SECTOR_TASK",
                "ordering": ("process_id", "due_at", "sector_code_snapshot"),
            },
        ),
        migrations.CreateModel(
            name="ProcessTaskGroupSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "origem de grupo da tarefa",
                "verbose_name_plural": "origens de grupo das tarefas",
                "db_table": "SGPD_TASK_GROUP_SOURCE",
                "ordering": ("task_id", "selected_group_id"),
            },
        ),
        migrations.CreateModel(
            name="ProcessValidationGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="selecionado em"),
                ),
            ],
            options={
                "verbose_name": "grupo selecionado do processo",
                "verbose_name_plural": "grupos selecionados dos processos",
                "db_table": "SGPD_PROCESS_GROUP",
                "ordering": ("process_id", "group_version_id"),
            },
        ),
        migrations.AddField(
            model_name="offboardingprocess",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="iniciado em"),
        ),
        migrations.AddField(
            model_name="offboardingprocess",
            name="started_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="started_offboarding_processes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="iniciado por",
            ),
        ),
        migrations.AlterField(
            model_name="offboardingprocess",
            name="status",
            field=models.CharField(
                choices=[("RASCUNHO", "Rascunho"), ("INICIADO", "Iniciado")],
                default="RASCUNHO",
                max_length=30,
                verbose_name="situação",
            ),
        ),
        migrations.AlterField(
            model_name="processauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("PROCESS_OPENED", "Processo aberto"),
                    ("DRAFT_SELECTION_UPDATED", "Seleção do rascunho alterada"),
                    ("PROCESS_STARTED", "Processo iniciado"),
                ],
                max_length=30,
                verbose_name="tipo do evento",
            ),
        ),
        migrations.AddConstraint(
            model_name="offboardingprocess",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("started_at__isnull", True),
                        ("started_by__isnull", True),
                        ("status", "RASCUNHO"),
                    ),
                    models.Q(
                        ("started_at__isnull", False),
                        ("started_by__isnull", False),
                        ("status", "INICIADO"),
                    ),
                    _connector="OR",
                ),
                name="SGPD_CK_PROCESS_START",
            ),
        ),
        migrations.AddField(
            model_name="processactionidempotency",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="offboarding_idempotent_actions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ator",
            ),
        ),
        migrations.AddField(
            model_name="processactionidempotency",
            name="process",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="idempotency_records",
                to="offboarding.offboardingprocess",
                verbose_name="processo",
            ),
        ),
        migrations.AddField(
            model_name="processchecklistitem",
            name="answered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="offboarding_checklist_answers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="respondido por",
            ),
        ),
        migrations.AddField(
            model_name="processchecklistitem",
            name="source_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="process_snapshots",
                to="templates_engine.checklisttemplateitem",
                verbose_name="item de origem",
            ),
        ),
        migrations.AddField(
            model_name="processsectoroverride",
            name="changed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="offboarding_sector_overrides",
                to=settings.AUTH_USER_MODEL,
                verbose_name="alterado por",
            ),
        ),
        migrations.AddField(
            model_name="processsectoroverride",
            name="process",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sector_overrides",
                to="offboarding.offboardingprocess",
                verbose_name="processo",
            ),
        ),
        migrations.AddField(
            model_name="processsectoroverride",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="process_overrides",
                to="sectors.validationsector",
                verbose_name="setor",
            ),
        ),
        migrations.AddField(
            model_name="processsectoroverride",
            name="template_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="process_overrides",
                to="templates_engine.checklisttemplateversion",
                verbose_name="versão do template",
            ),
        ),
        migrations.AddField(
            model_name="processsectortask",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="offboarding_tasks_completed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="concluída por",
            ),
        ),
        migrations.AddField(
            model_name="processsectortask",
            name="process",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sector_tasks",
                to="offboarding.offboardingprocess",
                verbose_name="processo",
            ),
        ),
        migrations.AddField(
            model_name="processsectortask",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="process_tasks",
                to="sectors.validationsector",
                verbose_name="setor",
            ),
        ),
        migrations.AddField(
            model_name="processsectortask",
            name="template_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="process_tasks",
                to="templates_engine.checklisttemplateversion",
                verbose_name="versão do template",
            ),
        ),
        migrations.AddField(
            model_name="processchecklistitem",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="checklist_items",
                to="offboarding.processsectortask",
                verbose_name="tarefa",
            ),
        ),
        migrations.AddField(
            model_name="processtaskgroupsource",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="group_sources",
                to="offboarding.processsectortask",
                verbose_name="tarefa",
            ),
        ),
        migrations.AddField(
            model_name="processvalidationgroup",
            name="group_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="process_selections",
                to="templates_engine.validationgroupversion",
                verbose_name="versão do grupo",
            ),
        ),
        migrations.AddField(
            model_name="processvalidationgroup",
            name="process",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="selected_groups",
                to="offboarding.offboardingprocess",
                verbose_name="processo",
            ),
        ),
        migrations.AddField(
            model_name="processvalidationgroup",
            name="selected_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="offboarding_groups_selected",
                to=settings.AUTH_USER_MODEL,
                verbose_name="selecionado por",
            ),
        ),
        migrations.AddField(
            model_name="processtaskgroupsource",
            name="selected_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generated_tasks",
                to="offboarding.processvalidationgroup",
                verbose_name="grupo selecionado",
            ),
        ),
        migrations.AddConstraint(
            model_name="processactionidempotency",
            constraint=models.UniqueConstraint(
                fields=("process", "action", "idempotency_key"),
                name="SGPD_UQ_PROCESS_IDEMPOTENCY",
            ),
        ),
        migrations.AddConstraint(
            model_name="processsectoroverride",
            constraint=models.UniqueConstraint(
                fields=("process", "sector"), name="SGPD_UQ_PROCESS_OVERRIDE"
            ),
        ),
        migrations.AddConstraint(
            model_name="processsectoroverride",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("action", "INCLUDE"), ("template_version__isnull", False)),
                    models.Q(("action", "EXCLUDE"), ("template_version__isnull", True)),
                    _connector="OR",
                ),
                name="SGPD_CK_PROCESS_OVERRIDE",
            ),
        ),
        migrations.AddConstraint(
            model_name="processsectoroverride",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("due_hours_override__isnull", True),
                    ("due_hours_override__gt", 0),
                    _connector="OR",
                ),
                name="SGPD_CK_PROC_OVERRIDE_DUE",
            ),
        ),
        migrations.AddIndex(
            model_name="processsectortask",
            index=models.Index(
                fields=["sector", "status", "due_at"], name="SGPD_IX_TASK_SECTOR_STATUS"
            ),
        ),
        migrations.AddIndex(
            model_name="processsectortask",
            index=models.Index(fields=["process", "status"], name="SGPD_IX_TASK_PROCESS_STATUS"),
        ),
        migrations.AddConstraint(
            model_name="processsectortask",
            constraint=models.UniqueConstraint(
                fields=("process", "sector"), name="SGPD_UQ_PROCESS_TASK"
            ),
        ),
        migrations.AddConstraint(
            model_name="processsectortask",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sla_hours_snapshot__gt", 0),
                    ("template_version_snapshot__gt", 0),
                    ("version__gt", 0),
                ),
                name="SGPD_CK_PROCESS_TASK_VALUES",
            ),
        ),
        migrations.AddConstraint(
            model_name="processchecklistitem",
            constraint=models.UniqueConstraint(
                fields=("task", "source_item"), name="SGPD_UQ_PROCESS_ITEM_SOURCE"
            ),
        ),
        migrations.AddConstraint(
            model_name="processchecklistitem",
            constraint=models.UniqueConstraint(
                fields=("task", "display_order"), name="SGPD_UQ_PROCESS_ITEM_ORDER"
            ),
        ),
        migrations.AddConstraint(
            model_name="processchecklistitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("display_order__gt", 0)),
                name="SGPD_CK_PROCESS_ITEM_ORDER",
            ),
        ),
        migrations.AddConstraint(
            model_name="processvalidationgroup",
            constraint=models.UniqueConstraint(
                fields=("process", "group_version"), name="SGPD_UQ_PROCESS_GROUP"
            ),
        ),
        migrations.AddConstraint(
            model_name="processtaskgroupsource",
            constraint=models.UniqueConstraint(
                fields=("task", "selected_group"), name="SGPD_UQ_TASK_GROUP_SOURCE"
            ),
        ),
    ]
