# Generated by Django 5.2.16 on 2026-07-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offboarding", "0002_processactionidempotency_processchecklistitem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("PROCESS_OPENED", "Processo aberto"),
                    ("DRAFT_SELECTION_UPDATED", "Seleção do rascunho alterada"),
                    ("PROCESS_STARTED", "Processo iniciado"),
                    ("SECTOR_TASK_STARTED", "Tarefa de setor iniciada"),
                    ("SECTOR_TASK_COMPLETED", "Tarefa de setor concluída"),
                ],
                max_length=30,
                verbose_name="tipo do evento",
            ),
        ),
        migrations.AlterField(
            model_name="processsectortask",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("EM_ANALISE", "Em análise"),
                    ("CONCLUIDA", "Concluída"),
                ],
                default="PENDENTE",
                max_length=30,
                verbose_name="situação",
            ),
        ),
    ]
