# Generated by Django 5.2.16 on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offboarding", "0003_alter_processauditevent_event_type_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="offboardingprocess",
            name="SGPD_CK_PROCESS_REQUIRED",
        ),
        migrations.RemoveField(
            model_name="offboardingprocess",
            name="manager",
        ),
        migrations.RemoveField(
            model_name="offboardingprocess",
            name="manager_email_snapshot",
        ),
        migrations.RemoveField(
            model_name="offboardingprocess",
            name="manager_name_snapshot",
        ),
        migrations.AddConstraint(
            model_name="offboardingprocess",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    status__isnull=False,
                    company_code__gt=0,
                    branch_code__gt=0,
                    employee_type_code__gt=0,
                    employee_registration__gt=0,
                    opened_by__isnull=False,
                    planned_termination_date__isnull=False,
                    due_date__isnull=False,
                    reason__isnull=False,
                    priority__isnull=False,
                ),
                name="SGPD_CK_PROCESS_REQUIRED",
            ),
        ),
    ]
