# Generated by Django 5.2.16 on 2026-07-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offboarding", "0004_remove_process_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("PROCESS_OPENED", "Processo aberto"),
                    ("DRAFT_SELECTION_UPDATED", "Seleção do rascunho alterada"),
                    ("PROCESS_STARTED", "Processo iniciado"),
                    ("SECTOR_TASK_STARTED", "Tarefa de setor iniciada"),
                    ("SECTOR_TASK_COMPLETED", "Tarefa de setor concluída"),
                    ("PENDING_CREATED", "Pendência criada"),
                    ("PENDING_COMMENTED", "Pendência comentada"),
                    ("PENDING_STATUS_CHANGED", "Situação da pendência alterada"),
                    ("EVIDENCE_UPLOADED", "Evidência enviada"),
                    ("EVIDENCE_DOWNLOADED", "Evidência baixada"),
                ],
                max_length=30,
                verbose_name="tipo do evento",
            ),
        ),
    ]
