# Generated by Django 5.2.16 on 2026-07-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offboarding", "0005_alter_processauditevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeesnapshot",
            name="branch_legal_name",
            field=models.CharField(max_length=255, verbose_name="nome da filial"),
        ),
    ]
