# Generated by Django 5.2.16 on 2026-07-31 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offboarding", "0008_alter_processauditevent_event_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="offboardingprocess",
            name="SGPD_CK_PROCESS_START",
        ),
        migrations.AddField(
            model_name="offboardingprocess",
            name="cancellation_reason",
            field=models.CharField(
                blank=True, max_length=1000, verbose_name="motivo do cancelamento"
            ),
        ),
        migrations.AddField(
            model_name="offboardingprocess",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="cancelado em"),
        ),
        migrations.AddField(
            model_name="offboardingprocess",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cancelled_offboarding_processes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="cancelado por",
            ),
        ),
        migrations.AddField(
            model_name="offboardingprocess",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="encerrado em"),
        ),
        migrations.AddField(
            model_name="offboardingprocess",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="closed_offboarding_processes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="encerrado por",
            ),
        ),
        migrations.AddField(
            model_name="offboardingprocess",
            name="closing_notes",
            field=models.CharField(
                blank=True, max_length=1000, verbose_name="observação do encerramento"
            ),
        ),
        migrations.AddField(
            model_name="offboardingprocess",
            name="processing_notes",
            field=models.CharField(
                blank=True, max_length=1000, verbose_name="observação do processamento"
            ),
        ),
        migrations.AddField(
            model_name="offboardingprocess",
            name="processing_registered_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="processamento registrado em"
            ),
        ),
        migrations.AddField(
            model_name="offboardingprocess",
            name="processing_registered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="processed_offboarding_processes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="processamento registrado por",
            ),
        ),
        migrations.AddField(
            model_name="offboardingprocess",
            name="release_notes",
            field=models.CharField(
                blank=True, max_length=1000, verbose_name="parecer da liberação"
            ),
        ),
        migrations.AddField(
            model_name="offboardingprocess",
            name="released_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="liberado em"),
        ),
        migrations.AddField(
            model_name="offboardingprocess",
            name="released_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="released_offboarding_processes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="liberado por",
            ),
        ),
        migrations.AddField(
            model_name="offboardingprocess",
            name="termination_processed_on",
            field=models.DateField(
                blank=True, null=True, verbose_name="data declarada do processamento"
            ),
        ),
        migrations.AddField(
            model_name="offboardingprocess",
            name="termination_reference",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="número declarado da rescisão"
            ),
        ),
        migrations.AlterField(
            model_name="offboardingprocess",
            name="status",
            field=models.CharField(
                choices=[
                    ("RASCUNHO", "Rascunho"),
                    ("INICIADO", "Iniciado"),
                    ("LIBERADO_PARA_RESCISAO", "Liberado para rescisão"),
                    ("RESCISAO_PROCESSADA", "Rescisão processada"),
                    ("ENCERRADO", "Encerrado"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="RASCUNHO",
                max_length=30,
                verbose_name="situação",
            ),
        ),
        migrations.AlterField(
            model_name="processauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("PROCESS_OPENED", "Processo aberto"),
                    ("DRAFT_SELECTION_UPDATED", "Seleção do rascunho alterada"),
                    ("PROCESS_STARTED", "Processo iniciado"),
                    ("SECTOR_TASK_STARTED", "Tarefa de setor iniciada"),
                    ("SECTOR_TASK_COMPLETED", "Tarefa de setor concluída"),
                    ("SECTOR_TASK_CANCELLED", "Tarefa de setor cancelada"),
                    ("PROCESS_RELEASED", "Processo liberado para rescisão"),
                    ("PROCESSING_REGISTERED", "Processamento da rescisão registrado"),
                    ("PROCESS_CLOSED", "Processo encerrado"),
                    ("PROCESS_CANCELLED", "Processo cancelado"),
                    ("PROCESS_REOPENED", "Processo reaberto"),
                    ("PENDING_CREATED", "Pendência criada"),
                    ("PENDING_COMMENTED", "Pendência comentada"),
                    ("PENDING_STATUS_CHANGED", "Situação da pendência alterada"),
                    ("PENDING_AMOUNT_INFORMED", "Valor informado"),
                    ("PENDING_AMOUNT_ASSESSED", "Valor apurado"),
                    ("PENDING_AMOUNT_CONTESTED", "Valor contestado"),
                    ("PENDING_AMOUNT_DECIDED", "Valor decidido"),
                    ("NOTIFICATION_REPROCESSED", "Notificação reprocessada"),
                    ("EVIDENCE_UPLOADED", "Evidência enviada"),
                    ("EVIDENCE_DOWNLOADED", "Evidência baixada"),
                ],
                max_length=30,
                verbose_name="tipo do evento",
            ),
        ),
        migrations.AlterField(
            model_name="processsectortask",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("EM_ANALISE", "Em análise"),
                    ("CONCLUIDA", "Concluída"),
                    ("CANCELADA", "Cancelada"),
                ],
                default="PENDENTE",
                max_length=30,
                verbose_name="situação",
            ),
        ),
        migrations.AddConstraint(
            model_name="offboardingprocess",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("started_at__isnull", True),
                        ("started_by__isnull", True),
                        ("status", "RASCUNHO"),
                    ),
                    models.Q(
                        ("started_at__isnull", False),
                        ("started_by__isnull", False),
                        (
                            "status__in",
                            (
                                "INICIADO",
                                "LIBERADO_PARA_RESCISAO",
                                "RESCISAO_PROCESSADA",
                                "ENCERRADO",
                            ),
                        ),
                    ),
                    models.Q(
                        ("started_at__isnull", True),
                        ("started_by__isnull", True),
                        ("status", "CANCELADO"),
                    ),
                    models.Q(
                        ("started_at__isnull", False),
                        ("started_by__isnull", False),
                        ("status", "CANCELADO"),
                    ),
                    _connector="OR",
                ),
                name="SGPD_CK_PROCESS_START",
            ),
        ),
        migrations.AddConstraint(
            model_name="offboardingprocess",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("closed_at__isnull", True),
                        ("closed_by__isnull", True),
                        ("processing_registered_at__isnull", True),
                        ("processing_registered_by__isnull", True),
                        ("released_at__isnull", True),
                        ("released_by__isnull", True),
                        ("status__in", ("RASCUNHO", "INICIADO", "CANCELADO")),
                    ),
                    models.Q(
                        ("closed_at__isnull", True),
                        ("closed_by__isnull", True),
                        ("processing_registered_at__isnull", True),
                        ("processing_registered_by__isnull", True),
                        ("released_at__isnull", False),
                        ("released_by__isnull", False),
                        ("status", "LIBERADO_PARA_RESCISAO"),
                    ),
                    models.Q(
                        ("closed_at__isnull", True),
                        ("closed_by__isnull", True),
                        ("processing_registered_at__isnull", False),
                        ("processing_registered_by__isnull", False),
                        ("released_at__isnull", False),
                        ("released_by__isnull", False),
                        ("status", "RESCISAO_PROCESSADA"),
                        ("termination_processed_on__isnull", False),
                        ("termination_reference__isnull", False),
                    ),
                    models.Q(
                        ("closed_at__isnull", False),
                        ("closed_by__isnull", False),
                        ("processing_registered_at__isnull", False),
                        ("processing_registered_by__isnull", False),
                        ("released_at__isnull", False),
                        ("released_by__isnull", False),
                        ("status", "ENCERRADO"),
                    ),
                    _connector="OR",
                ),
                name="SGPD_CK_PROCESS_FORMAL",
            ),
        ),
        migrations.AddConstraint(
            model_name="offboardingprocess",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("cancelled_at__isnull", True),
                        ("cancelled_by__isnull", True),
                        (
                            "status__in",
                            (
                                "RASCUNHO",
                                "INICIADO",
                                "LIBERADO_PARA_RESCISAO",
                                "RESCISAO_PROCESSADA",
                                "ENCERRADO",
                            ),
                        ),
                    ),
                    models.Q(
                        ("cancellation_reason__isnull", False),
                        ("cancelled_at__isnull", False),
                        ("cancelled_by__isnull", False),
                        ("status", "CANCELADO"),
                    ),
                    _connector="OR",
                ),
                name="SGPD_CK_PROCESS_CANCEL",
            ),
        ),
    ]
