# Generated by Django 5.2.16 on 2026-07-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offboarding", "0009_process_formal_lifecycle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("PROCESS_OPENED", "Processo aberto"),
                    ("DRAFT_SELECTION_UPDATED", "Seleção do rascunho alterada"),
                    ("PROCESS_STARTED", "Processo iniciado"),
                    ("SECTOR_TASK_STARTED", "Tarefa de setor iniciada"),
                    ("SECTOR_TASK_COMPLETED", "Tarefa de setor concluída"),
                    ("SECTOR_TASK_CANCELLED", "Tarefa de setor cancelada"),
                    ("SECTOR_TASK_REOPENED", "Tarefa de setor reaberta"),
                    ("PROCESS_RELEASED", "Processo liberado para rescisão"),
                    ("PROCESSING_REGISTERED", "Processamento da rescisão registrado"),
                    ("PROCESS_CLOSED", "Processo encerrado"),
                    ("PROCESS_CANCELLED", "Processo cancelado"),
                    ("PROCESS_REOPENED", "Processo reaberto"),
                    ("PENDING_CREATED", "Pendência criada"),
                    ("PENDING_COMMENTED", "Pendência comentada"),
                    ("PENDING_STATUS_CHANGED", "Situação da pendência alterada"),
                    ("PENDING_AMOUNT_INFORMED", "Valor informado"),
                    ("PENDING_AMOUNT_ASSESSED", "Valor apurado"),
                    ("PENDING_AMOUNT_CONTESTED", "Valor contestado"),
                    ("PENDING_AMOUNT_DECIDED", "Valor decidido"),
                    ("NOTIFICATION_REPROCESSED", "Notificação reprocessada"),
                    ("EVIDENCE_UPLOADED", "Evidência enviada"),
                    ("EVIDENCE_DOWNLOADED", "Evidência baixada"),
                ],
                max_length=30,
                verbose_name="tipo do evento",
            ),
        ),
    ]
