# Generated by Django 5.2.16 on 2026-08-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offboarding", "0010_cancel_and_reopen_events"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offboardingprocess",
            options={
                "ordering": ("-opened_at", "-id"),
                "permissions": [
                    (
                        "override_process_blockers",
                        "Pode liberar e encerrar processo com impedimentos, mediante justificativa",
                    )
                ],
                "verbose_name": "processo demissional",
                "verbose_name_plural": "processos demissionais",
            },
        ),
        migrations.AddField(
            model_name="offboardingprocess",
            name="closing_override_reason",
            field=models.CharField(
                blank=True,
                max_length=1000,
                verbose_name="justificativa do override de impedimentos no encerramento",
            ),
        ),
        migrations.AddField(
            model_name="offboardingprocess",
            name="release_override_reason",
            field=models.CharField(
                blank=True,
                max_length=1000,
                verbose_name="justificativa do override de impedimentos na liberação",
            ),
        ),
    ]
