# Generated by Django 5.2.16 on 2026-08-06 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offboarding", "0011_alter_offboardingprocess_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="offboardingprocess",
            name="SGPD_CK_PROCESS_FORMAL",
        ),
        migrations.AddConstraint(
            model_name="offboardingprocess",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("closed_at__isnull", True),
                        ("closed_by__isnull", True),
                        ("processing_registered_at__isnull", True),
                        ("processing_registered_by__isnull", True),
                        ("released_at__isnull", True),
                        ("released_by__isnull", True),
                        ("status__in", ("RASCUNHO", "INICIADO")),
                    ),
                    models.Q(
                        ("closed_at__isnull", True),
                        ("closed_by__isnull", True),
                        ("processing_registered_at__isnull", True),
                        ("processing_registered_by__isnull", True),
                        ("released_at__isnull", False),
                        ("released_by__isnull", False),
                        ("status", "LIBERADO_PARA_RESCISAO"),
                    ),
                    models.Q(
                        ("closed_at__isnull", True),
                        ("closed_by__isnull", True),
                        ("processing_registered_at__isnull", False),
                        ("processing_registered_by__isnull", False),
                        ("released_at__isnull", False),
                        ("released_by__isnull", False),
                        ("status", "RESCISAO_PROCESSADA"),
                        ("termination_processed_on__isnull", False),
                        ("termination_reference__isnull", False),
                    ),
                    models.Q(
                        ("closed_at__isnull", False),
                        ("closed_by__isnull", False),
                        ("processing_registered_at__isnull", False),
                        ("processing_registered_by__isnull", False),
                        ("released_at__isnull", False),
                        ("released_by__isnull", False),
                        ("status", "ENCERRADO"),
                    ),
                    models.Q(
                        ("closed_at__isnull", True),
                        ("closed_by__isnull", True),
                        ("processing_registered_at__isnull", True),
                        ("processing_registered_by__isnull", True),
                        ("released_at__isnull", True),
                        ("released_by__isnull", True),
                        ("status", "CANCELADO"),
                    ),
                    models.Q(
                        ("closed_at__isnull", True),
                        ("closed_by__isnull", True),
                        ("processing_registered_at__isnull", True),
                        ("processing_registered_by__isnull", True),
                        ("released_at__isnull", False),
                        ("released_by__isnull", False),
                        ("status", "CANCELADO"),
                    ),
                    models.Q(
                        ("closed_at__isnull", True),
                        ("closed_by__isnull", True),
                        ("processing_registered_at__isnull", False),
                        ("processing_registered_by__isnull", False),
                        ("released_at__isnull", False),
                        ("released_by__isnull", False),
                        ("status", "CANCELADO"),
                        ("termination_processed_on__isnull", False),
                        ("termination_reference__isnull", False),
                    ),
                    models.Q(
                        ("closed_at__isnull", False),
                        ("closed_by__isnull", False),
                        ("processing_registered_at__isnull", False),
                        ("processing_registered_by__isnull", False),
                        ("released_at__isnull", False),
                        ("released_by__isnull", False),
                        ("status", "CANCELADO"),
                        ("termination_processed_on__isnull", False),
                        ("termination_reference__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="SGPD_CK_PROCESS_FORMAL",
            ),
        ),
    ]
