# Generated by Django 5.2.16 on 2026-08-06 11:15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offboarding", "0012_cancel_preserves_formal_marks"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offboardingprocess",
            options={
                "ordering": ("-opened_at", "-id"),
                "permissions": [
                    (
                        "override_process_blockers",
                        "Pode passar por cima de impedimentos, cancelar processo já "
                        "formalizado e excluir processo com histórico, sempre mediante "
                        "justificativa",
                    )
                ],
                "verbose_name": "processo demissional",
                "verbose_name_plural": "processos demissionais",
            },
        ),
        migrations.CreateModel(
            name="ProcessPurgeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "process_uuid",
                    models.UUIDField(
                        editable=False,
                        unique=True,
                        verbose_name="UUID do processo excluído",
                    ),
                ),
                (
                    "process_status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("INICIADO", "Iniciado"),
                            ("LIBERADO_PARA_RESCISAO", "Liberado para rescisão"),
                            ("RESCISAO_PROCESSADA", "Rescisão processada"),
                            ("ENCERRADO", "Encerrado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        max_length=30,
                        verbose_name="situação no momento da exclusão",
                    ),
                ),
                (
                    "company_code",
                    models.PositiveIntegerField(verbose_name="código da empresa"),
                ),
                (
                    "branch_code",
                    models.PositiveIntegerField(verbose_name="código da filial"),
                ),
                (
                    "employee_type_code",
                    models.PositiveIntegerField(verbose_name="tipo de colaborador"),
                ),
                (
                    "employee_registration",
                    models.PositiveIntegerField(verbose_name="matrícula"),
                ),
                (
                    "employee_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="nome do colaborador"
                    ),
                ),
                ("opened_at", models.DateTimeField(verbose_name="processo aberto em")),
                (
                    "purged_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="excluído em"),
                ),
                (
                    "reason",
                    models.CharField(max_length=1000, verbose_name="justificativa da exclusão"),
                ),
                (
                    "had_material_history",
                    models.BooleanField(default=False, verbose_name="possuía histórico material"),
                ),
                (
                    "deleted_counts",
                    models.JSONField(blank=True, default=dict, verbose_name="linhas excluídas"),
                ),
                (
                    "audit_trail",
                    models.JSONField(blank=True, default=list, verbose_name="trilha copiada"),
                ),
                (
                    "evidence_files",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="arquivos de evidência removidos",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(max_length=64, verbose_name="chave de idempotência"),
                ),
                (
                    "correlation_id",
                    models.CharField(default="-", max_length=64, verbose_name="correlation ID"),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purged_offboarding_processes_opened",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="processo aberto por",
                    ),
                ),
                (
                    "purged_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purged_offboarding_processes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="excluído por",
                    ),
                ),
            ],
            options={
                "verbose_name": "exclusão de processo",
                "verbose_name_plural": "exclusões de processos",
                "db_table": "SGPD_PROCESS_PURGE",
                "ordering": ("-purged_at", "-id"),
                "indexes": [
                    models.Index(fields=["purged_at"], name="SGPD_IX_PURGE_AT"),
                    models.Index(
                        fields=["company_code", "branch_code", "employee_registration"],
                        name="SGPD_IX_PURGE_EMPLOYEE",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("branch_code__gt", 0),
                            ("company_code__gt", 0),
                            ("employee_registration__gt", 0),
                            ("employee_type_code__gt", 0),
                            ("idempotency_key__isnull", False),
                            ("opened_by__isnull", False),
                            ("process_status__isnull", False),
                            ("process_uuid__isnull", False),
                            ("purged_by__isnull", False),
                            ("reason__isnull", False),
                        ),
                        name="SGPD_CK_PROCESS_PURGE_REQ",
                    )
                ],
            },
        ),
    ]
