# Generated by Django 5.2.16 on 2026-08-01 00:02

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "dataset",
                    models.CharField(
                        choices=[
                            ("PROCESSOS", "Processos"),
                            ("TAREFAS", "Tarefas de setor"),
                            ("PENDENCIAS", "Pendências e valores"),
                        ],
                        max_length=20,
                        verbose_name="conjunto",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="início do período")),
                ("period_end", models.DateField(verbose_name="fim do período")),
                (
                    "row_count",
                    models.PositiveIntegerField(verbose_name="linhas exportadas"),
                ),
                (
                    "exported_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="exportado em"),
                ),
                (
                    "correlation_id",
                    models.CharField(default="-", max_length=64, verbose_name="correlation ID"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_exports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ator",
                    ),
                ),
            ],
            options={
                "verbose_name": "exportação de relatório",
                "verbose_name_plural": "exportações de relatórios",
                "db_table": "SGPD_REPORT_EXPORT",
                "ordering": ("-exported_at", "-id"),
                "indexes": [
                    models.Index(fields=["actor", "exported_at"], name="SGPD_IX_EXPORT_ACTOR")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("period_start__lte", models.F("period_end"))),
                        name="SGPD_CK_EXPORT_PERIOD",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("correlation_id__isnull", False),
                            ("dataset__isnull", False),
                        ),
                        name="SGPD_CK_EXPORT_REQUIRED",
                    ),
                ],
            },
        ),
    ]
