# Generated by Django 5.2.16 on 2026-07-28 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.system_settings.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LdapConfiguration",
            fields=[
                (
                    "key",
                    models.CharField(
                        default="PRIMARY",
                        editable=False,
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                        verbose_name="chave",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=False, verbose_name="descoberta habilitada"),
                ),
                (
                    "authentication_enabled",
                    models.BooleanField(default=False, verbose_name="autenticação habilitada"),
                ),
                (
                    "server_uri",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        verbose_name="URI do servidor",
                    ),
                ),
                (
                    "bind_dn",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        verbose_name="identidade de bind",
                    ),
                ),
                (
                    "bind_password_ciphertext",
                    models.TextField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="senha de bind cifrada",
                    ),
                ),
                (
                    "user_search_base",
                    models.CharField(
                        blank=True,
                        max_length=2000,
                        verbose_name="base de usuários",
                    ),
                ),
                (
                    "group_search_base",
                    models.CharField(
                        blank=True,
                        max_length=2000,
                        verbose_name="base de grupos",
                    ),
                ),
                (
                    "required_group_dn",
                    models.CharField(
                        blank=True,
                        max_length=2000,
                        verbose_name="grupo obrigatório",
                    ),
                ),
                (
                    "start_tls",
                    models.BooleanField(default=False, verbose_name="usar StartTLS"),
                ),
                (
                    "allow_insecure_discovery",
                    models.BooleanField(
                        default=False,
                        verbose_name="permitir descoberta sem TLS no DEV",
                    ),
                ),
                (
                    "connect_timeout_seconds",
                    models.PositiveSmallIntegerField(
                        default=5,
                        verbose_name="timeout de conexão em segundos",
                    ),
                ),
                (
                    "receive_timeout_seconds",
                    models.PositiveSmallIntegerField(
                        default=10,
                        verbose_name="timeout de resposta em segundos",
                    ),
                ),
                (
                    "page_size",
                    models.PositiveSmallIntegerField(
                        default=100,
                        verbose_name="tamanho da página LDAP",
                    ),
                ),
                (
                    "result_limit",
                    models.PositiveSmallIntegerField(
                        default=50,
                        verbose_name="limite de resultados",
                    ),
                ),
                (
                    "nested_group_search",
                    models.BooleanField(
                        default=True,
                        verbose_name="buscar grupos aninhados",
                    ),
                ),
                (
                    "local_superuser_fallback",
                    models.BooleanField(
                        default=True,
                        verbose_name="preservar contingência local de SuperAdmin",
                    ),
                ),
                (
                    "user_extra_filter",
                    models.CharField(
                        blank=True,
                        max_length=2000,
                        verbose_name="filtro adicional de usuários",
                    ),
                ),
                (
                    "certificate_file",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        storage=apps.system_settings.storage.system_configuration_storage,
                        upload_to="ldap-ca/",
                        verbose_name="arquivo da CA",
                    ),
                ),
                (
                    "certificate_original_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="nome original da CA",
                    ),
                ),
                (
                    "certificate_sha256",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="SHA-256 da CA",
                    ),
                ),
                (
                    "certificate_subject",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        verbose_name="subject da CA",
                    ),
                ),
                (
                    "certificate_issuer",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        verbose_name="issuer da CA",
                    ),
                ),
                (
                    "certificate_not_before",
                    models.DateTimeField(blank=True, null=True, verbose_name="CA válida desde"),
                ),
                (
                    "certificate_not_after",
                    models.DateTimeField(blank=True, null=True, verbose_name="CA válida até"),
                ),
                (
                    "certificate_count",
                    models.PositiveSmallIntegerField(
                        default=0,
                        verbose_name="certificados no bundle",
                    ),
                ),
                (
                    "certificate_uploaded_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="CA enviada em"),
                ),
                (
                    "last_tested_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="último teste em"),
                ),
                (
                    "last_test_success",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="último teste passou",
                    ),
                ),
                (
                    "last_test_fingerprint",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="fingerprint da configuração testada",
                    ),
                ),
                (
                    "last_test_duration_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="duração do último teste em ms",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        verbose_name="versão de concorrência",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "certificate_uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ldap_certificates_uploaded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="CA enviada por",
                    ),
                ),
                (
                    "last_tested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ldap_connections_tested",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="último teste por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ldap_configurations_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "configuração LDAP",
                "verbose_name_plural": "configurações LDAP",
                "db_table": "SGPD_LDAP_CONFIG",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("version__gt", 0)),
                        name="SGPD_CK_LDAP_VERSION",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("connect_timeout_seconds__gt", 0),
                            ("page_size__gt", 0),
                            ("receive_timeout_seconds__gt", 0),
                            ("result_limit__gt", 0),
                        ),
                        name="SGPD_CK_LDAP_LIMITS",
                    ),
                ],
            },
        ),
    ]
