# Generated by Django 5.2.16 on 2026-07-28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system_settings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ldapconfiguration",
            name="allow_insecure_discovery",
        ),
    ]
