# Generated by Django 5.2.16 on 2026-07-31 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_settings", "0002_remove_ldap_insecure_discovery"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailConfiguration",
            fields=[
                (
                    "key",
                    models.CharField(
                        default="PRIMARY",
                        editable=False,
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                        verbose_name="chave",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=False, verbose_name="envio habilitado"),
                ),
                (
                    "host",
                    models.CharField(blank=True, max_length=255, verbose_name="servidor SMTP"),
                ),
                (
                    "port",
                    models.PositiveIntegerField(default=587, verbose_name="porta"),
                ),
                (
                    "use_tls",
                    models.BooleanField(default=True, verbose_name="usar TLS/STARTTLS"),
                ),
                (
                    "username",
                    models.CharField(blank=True, max_length=255, verbose_name="usuário SMTP"),
                ),
                (
                    "password_ciphertext",
                    models.TextField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="senha SMTP cifrada",
                    ),
                ),
                (
                    "timeout_seconds",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="timeout em segundos"
                    ),
                ),
                (
                    "default_from_email",
                    models.CharField(blank=True, max_length=254, verbose_name="remetente padrão"),
                ),
                (
                    "base_url",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="URL base da aplicação"
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveSmallIntegerField(default=5, verbose_name="tentativas máximas"),
                ),
                (
                    "batch_size",
                    models.PositiveSmallIntegerField(
                        default=50, verbose_name="mensagens por despacho"
                    ),
                ),
                (
                    "stale_minutes",
                    models.PositiveSmallIntegerField(
                        default=15, verbose_name="minutos para reabrir envio"
                    ),
                ),
                (
                    "task_due_soon_hours",
                    models.PositiveSmallIntegerField(
                        default=48, verbose_name="horas do primeiro lembrete"
                    ),
                ),
                (
                    "task_due_imminent_hours",
                    models.PositiveSmallIntegerField(
                        default=24, verbose_name="horas do lembrete final"
                    ),
                ),
                (
                    "task_critical_hours",
                    models.PositiveSmallIntegerField(
                        default=48, verbose_name="horas para o atraso crítico"
                    ),
                ),
                (
                    "process_due_soon_hours",
                    models.PositiveSmallIntegerField(
                        default=72, verbose_name="horas do alerta do processo"
                    ),
                ),
                (
                    "last_tested_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="último teste em"),
                ),
                (
                    "last_test_success",
                    models.BooleanField(blank=True, null=True, verbose_name="último teste passou"),
                ),
                (
                    "last_test_recipient",
                    models.CharField(
                        blank=True, max_length=254, verbose_name="destinatário do teste"
                    ),
                ),
                (
                    "last_test_error",
                    models.TextField(blank=True, verbose_name="erro do último teste"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="versão de concorrência"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "last_tested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="email_configurations_tested",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="último teste por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="email_configurations_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "configuração de e-mail",
                "verbose_name_plural": "configurações de e-mail",
                "db_table": "SGPD_EMAIL_CONFIG",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("version__gt", 0)),
                        name="SGPD_CK_EMAIL_VERSION",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("port__gte", 1), ("port__lte", 65535)),
                        name="SGPD_CK_EMAIL_PORT",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("batch_size__gt", 0),
                            ("max_attempts__gt", 0),
                            ("stale_minutes__gt", 0),
                            ("timeout_seconds__gt", 0),
                        ),
                        name="SGPD_CK_EMAIL_QUEUE",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("process_due_soon_hours__gt", 0),
                            ("task_critical_hours__gt", 0),
                            ("task_due_imminent_hours__gt", 0),
                            ("task_due_soon_hours__gt", 0),
                        ),
                        name="SGPD_CK_EMAIL_MILESTONES",
                    ),
                ],
            },
        ),
    ]
