# Generated by Django 5.2.16 on 2026-07-30 14:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.evidence.models
import apps.evidence.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("offboarding", "0005_alter_processauditevent_event_type"),
        ("pending_items", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        storage=apps.evidence.storage.evidence_storage,
                        upload_to=apps.evidence.models.evidence_upload_to,
                        verbose_name="arquivo privado",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="nome original"),
                ),
                (
                    "mime_type",
                    models.CharField(max_length=120, verbose_name="MIME type"),
                ),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(verbose_name="tamanho em bytes"),
                ),
                (
                    "sha256",
                    models.CharField(max_length=64, verbose_name="hash SHA-256"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="enviada em"),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("INTERNA", "Interna"),
                            ("RESTRITA", "Restrita"),
                            ("SENSIVEL", "Sensível"),
                        ],
                        default="RESTRITA",
                        max_length=12,
                        verbose_name="classificação",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativa")),
                (
                    "checklist_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidences",
                        to="offboarding.processchecklistitem",
                        verbose_name="item de checklist",
                    ),
                ),
                (
                    "pending_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidences",
                        to="pending_items.pendingitem",
                        verbose_name="pendência",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidences",
                        to="offboarding.offboardingprocess",
                        verbose_name="processo",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidences",
                        to="offboarding.processsectortask",
                        verbose_name="tarefa",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidences_uploaded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="enviada por",
                    ),
                ),
            ],
            options={
                "db_table": "SGPD_EVIDENCE",
                "ordering": ("-uploaded_at", "-id"),
                "indexes": [
                    models.Index(fields=["process", "uploaded_at"], name="SGPD_IX_EVID_PROC_DATE"),
                    models.Index(fields=["task", "uploaded_at"], name="SGPD_IX_EVID_TASK_DATE"),
                    models.Index(fields=["sha256"], name="SGPD_IX_EVID_SHA256"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("size_bytes__gt", 0)),
                        name="SGPD_CK_EVIDENCE_SIZE",
                    )
                ],
            },
        ),
    ]
