# Generated by Django 5.2.16 on 2026-07-30 14:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("offboarding", "0005_alter_processauditevent_event_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MATERIAL", "Material"),
                            ("FERRAMENTA", "Ferramenta"),
                            ("EQUIPAMENTO", "Equipamento"),
                            ("DOCUMENTO", "Documento"),
                            ("ACESSO", "Acesso"),
                            ("EXAME", "Exame"),
                            ("ATIVIDADE", "Atividade"),
                            ("VEICULO", "Veículo"),
                            ("PATRIMONIO", "Patrimônio"),
                            ("CONTRATO", "Contrato"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="categoria",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="título")),
                ("description", models.TextField(verbose_name="descrição")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ABERTA", "Aberta"),
                            ("EM_REGULARIZACAO", "Em regularização"),
                            ("REGULARIZADA", "Regularizada"),
                            ("ENCERRADA", "Encerrada"),
                        ],
                        default="ABERTA",
                        max_length=24,
                        verbose_name="situação",
                    ),
                ),
                (
                    "blocking_level",
                    models.CharField(
                        choices=[
                            ("INFORMATIVA", "Informativa"),
                            ("NAO_BLOQUEANTE", "Não bloqueante"),
                            ("BLOQUEANTE", "Bloqueante"),
                        ],
                        default="BLOQUEANTE",
                        max_length=20,
                        verbose_name="classificação de bloqueio",
                    ),
                ),
                (
                    "identified_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="identificada em"),
                ),
                (
                    "regularization_due_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="limite de regularização"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizada em"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="versão de concorrência"),
                ),
                (
                    "checklist_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pending_items",
                        to="offboarding.processchecklistitem",
                        verbose_name="item de checklist",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pending_items",
                        to="offboarding.offboardingprocess",
                        verbose_name="processo",
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pending_items_registered",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="registrada por",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pending_items",
                        to="offboarding.processsectortask",
                        verbose_name="tarefa",
                    ),
                ),
            ],
            options={
                "db_table": "SGPD_PENDING_ITEM",
                "ordering": ("-identified_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="PendingComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="comentário")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pending_comments_authored",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="autor",
                    ),
                ),
                (
                    "pending_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comments",
                        to="pending_items.pendingitem",
                        verbose_name="pendência",
                    ),
                ),
            ],
            options={
                "db_table": "SGPD_PENDING_COMMENT",
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="PendingItemLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=80, verbose_name="código do item"),
                ),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="descrição"),
                ),
                (
                    "asset_tag",
                    models.CharField(blank=True, max_length=100, verbose_name="patrimônio"),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=120, verbose_name="número de série"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=1,
                        max_digits=12,
                        verbose_name="quantidade",
                    ),
                ),
                (
                    "unit",
                    models.CharField(default="UN", max_length=30, verbose_name="unidade"),
                ),
                (
                    "item_condition",
                    models.CharField(blank=True, max_length=120, verbose_name="estado do item"),
                ),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="dados adicionais"),
                ),
                (
                    "pending_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="pending_items.pendingitem",
                        verbose_name="pendência",
                    ),
                ),
            ],
            options={
                "db_table": "SGPD_PENDING_ITEM_LINE",
                "ordering": ("pending_item_id", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="pendingitem",
            index=models.Index(
                fields=["process", "status", "blocking_level"],
                name="SGPD_IX_PEND_PROC_STATUS",
            ),
        ),
        migrations.AddIndex(
            model_name="pendingitem",
            index=models.Index(fields=["task", "status"], name="SGPD_IX_PEND_TASK_STATUS"),
        ),
        migrations.AddConstraint(
            model_name="pendingitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gt", 0)), name="SGPD_CK_PENDING_VERSION"
            ),
        ),
        migrations.AddConstraint(
            model_name="pendingitemline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="SGPD_CK_PEND_LINE_QTY"
            ),
        ),
    ]
