# Generated by Django 5.2.16 on 2026-07-31 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pending_items", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingitem",
            name="blocking_level",
            field=models.CharField(
                choices=[
                    ("INFORMATIVA", "Informativa"),
                    ("NAO_BLOQUEANTE", "Não bloqueante"),
                    ("BLOQUEANTE", "Bloqueante"),
                    ("BLOQUEANTE_ATE_DECISAO", "Bloqueante até decisão"),
                ],
                default="BLOQUEANTE",
                max_length=24,
                verbose_name="classificação de bloqueio",
            ),
        ),
        migrations.AlterField(
            model_name="pendingitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("VALOR", "Valor"),
                    ("MATERIAL", "Material"),
                    ("FERRAMENTA", "Ferramenta"),
                    ("EQUIPAMENTO", "Equipamento"),
                    ("DOCUMENTO", "Documento"),
                    ("ACESSO", "Acesso"),
                    ("EXAME", "Exame"),
                    ("ATIVIDADE", "Atividade"),
                    ("VEICULO", "Veículo"),
                    ("PATRIMONIO", "Patrimônio"),
                    ("CONTRATO", "Contrato"),
                    ("OUTRO", "Outro"),
                ],
                max_length=20,
                verbose_name="categoria",
            ),
        ),
        migrations.AlterField(
            model_name="pendingitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("ABERTA", "Aberta"),
                    ("EM_REGULARIZACAO", "Em regularização"),
                    ("REGULARIZADA", "Regularizada"),
                    ("ENCAMINHADA_ANALISE", "Encaminhada para análise"),
                    ("CONTESTADA", "Contestada"),
                    ("APROVADA_COBRANCA", "Aprovada para cobrança"),
                    ("REJEITADA", "Rejeitada"),
                    ("ABONADA", "Abonada"),
                    ("ENCERRADA", "Encerrada"),
                ],
                default="ABERTA",
                max_length=24,
                verbose_name="situação",
            ),
        ),
        migrations.CreateModel(
            name="PendingDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision_type",
                    models.CharField(
                        choices=[("VALOR", "Valor")],
                        default="VALOR",
                        max_length=20,
                        verbose_name="tipo da decisão",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("APROVADA_COBRANCA", "Aprovada para cobrança"),
                            ("REJEITADA", "Rejeitada"),
                            ("ABONADA", "Abonada"),
                        ],
                        max_length=24,
                        verbose_name="decisão",
                    ),
                ),
                ("opinion", models.TextField(verbose_name="parecer")),
                (
                    "decided_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="decidida em"),
                ),
                (
                    "segregation_override",
                    models.BooleanField(
                        default=False,
                        help_text="Verdadeiro quando o decisor é quem informou o valor.",
                        verbose_name="segregação dispensada",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pending_decisions_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="decidida por",
                    ),
                ),
                (
                    "pending_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="pending_items.pendingitem",
                        verbose_name="pendência",
                    ),
                ),
            ],
            options={
                "db_table": "SGPD_PENDING_DECISION",
                "ordering": ("decided_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="PendingAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_informed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="valor informado",
                    ),
                ),
                (
                    "amount_assessed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="valor apurado",
                    ),
                ),
                (
                    "amount_contested",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="valor contestado",
                    ),
                ),
                (
                    "amount_approved",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="valor aprovado",
                    ),
                ),
                (
                    "amount_processed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="valor processado",
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="BRL", max_length=3, verbose_name="moeda"),
                ),
                ("justification", models.TextField(verbose_name="justificativa")),
                (
                    "informed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="informado em"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="aprovado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="versão de concorrência"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pending_amounts_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="aprovado por",
                    ),
                ),
                (
                    "informed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pending_amounts_informed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="informado por",
                    ),
                ),
                (
                    "pending_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="amount",
                        to="pending_items.pendingitem",
                        verbose_name="pendência",
                    ),
                ),
            ],
            options={
                "db_table": "SGPD_PENDING_AMOUNT",
                "ordering": ("pending_item_id",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("version__gt", 0)),
                        name="SGPD_CK_PAMOUNT_VERSION",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount_informed__gte", 0)),
                        name="SGPD_CK_PAMOUNT_INFORMED",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount_assessed__gte", 0)),
                        name="SGPD_CK_PAMOUNT_ASSESSED",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount_contested__gte", 0)),
                        name="SGPD_CK_PAMOUNT_CONTESTED",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount_approved__gte", 0)),
                        name="SGPD_CK_PAMOUNT_APPROVED",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount_processed__gte", 0)),
                        name="SGPD_CK_PAMOUNT_PROCESSED",
                    ),
                ],
            },
        ),
    ]
