# Generated by Django 5.2.16 on 2026-07-29 15:52

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sectors", "0003_responsibility_inherits_sector_scope"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidationGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="código"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nome")),
                ("description", models.TextField(blank=True, verbose_name="descrição")),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="versão de concorrência"),
                ),
            ],
            options={
                "verbose_name": "grupo de validação",
                "verbose_name_plural": "grupos de validação",
                "db_table": "SGPD_VALIDATION_GROUP",
                "ordering": ("code",),
                "permissions": [
                    (
                        "manage_workflow_configuration",
                        "Pode criar e publicar grupos e templates",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ChecklistTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="código"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nome")),
                ("description", models.TextField(blank=True, verbose_name="descrição")),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="versão de concorrência"),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checklist_templates",
                        to="sectors.validationsector",
                        verbose_name="setor",
                    ),
                ),
            ],
            options={
                "verbose_name": "template de checklist",
                "verbose_name_plural": "templates de checklist",
                "db_table": "SGPD_CHECKLIST_TEMPLATE",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="ChecklistTemplateVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(verbose_name="número da versão"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("PUBLISHED", "Publicada"),
                            ("RETIRED", "Substituída"),
                        ],
                        default="DRAFT",
                        max_length=12,
                        verbose_name="situação",
                    ),
                ),
                (
                    "default_due_hours",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="prazo padrão em horas"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criada em"),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="publicada em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checklist_template_versions_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criada por",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checklist_template_versions_published",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="publicada por",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="templates_engine.checklisttemplate",
                        verbose_name="template",
                    ),
                ),
            ],
            options={
                "verbose_name": "versão de template",
                "verbose_name_plural": "versões de templates",
                "db_table": "SGPD_CHECKLIST_TEMPLATE_VER",
                "ordering": ("template__code", "-version_number"),
            },
        ),
        migrations.CreateModel(
            name="ChecklistTemplateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, verbose_name="código")),
                ("question", models.TextField(verbose_name="pergunta")),
                (
                    "response_type",
                    models.CharField(
                        choices=[
                            ("BOOLEAN", "Sim/Não"),
                            ("TEXT", "Texto"),
                            ("NUMBER", "Número"),
                            ("DATE", "Data"),
                            ("SINGLE_CHOICE", "Seleção"),
                            ("MULTIPLE_CHOICE", "Múltipla seleção"),
                            ("FILE", "Arquivo"),
                            ("CONFIRMATION", "Confirmação obrigatória"),
                        ],
                        max_length=20,
                        verbose_name="tipo de resposta",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="obrigatório"),
                ),
                (
                    "blocks_process",
                    models.BooleanField(default=False, verbose_name="bloqueia o processo"),
                ),
                (
                    "requires_evidence",
                    models.BooleanField(default=False, verbose_name="exige evidência"),
                ),
                (
                    "allows_pending",
                    models.BooleanField(default=True, verbose_name="permite pendência"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(verbose_name="ordem de exibição"),
                ),
                (
                    "config",
                    models.JSONField(blank=True, default=dict, verbose_name="configuração"),
                ),
                (
                    "template_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="templates_engine.checklisttemplateversion",
                        verbose_name="versão do template",
                    ),
                ),
            ],
            options={
                "verbose_name": "item de template",
                "verbose_name_plural": "itens de template",
                "db_table": "SGPD_CHECKLIST_TEMPLATE_ITEM",
                "ordering": ("template_version_id", "display_order", "id"),
            },
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="templates_engine.checklisttemplateversion",
                verbose_name="versão vigente",
            ),
        ),
        migrations.CreateModel(
            name="ValidationGroupVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(verbose_name="número da versão"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("PUBLISHED", "Publicada"),
                            ("RETIRED", "Substituída"),
                        ],
                        default="DRAFT",
                        max_length=12,
                        verbose_name="situação",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criada em"),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="publicada em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validation_group_versions_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criada por",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="templates_engine.validationgroup",
                        verbose_name="grupo",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validation_group_versions_published",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="publicada por",
                    ),
                ),
            ],
            options={
                "verbose_name": "versão de grupo",
                "verbose_name_plural": "versões de grupos",
                "db_table": "SGPD_VALIDATION_GROUP_VER",
                "ordering": ("group__code", "-version_number"),
            },
        ),
        migrations.CreateModel(
            name="ValidationGroupSector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="obrigatório"),
                ),
                (
                    "blocks_process",
                    models.BooleanField(default=True, verbose_name="bloqueia o processo"),
                ),
                (
                    "due_hours_override",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="prazo específico em horas"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(verbose_name="ordem de exibição"),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validation_group_rules",
                        to="sectors.validationsector",
                        verbose_name="setor",
                    ),
                ),
                (
                    "template_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validation_group_rules",
                        to="templates_engine.checklisttemplateversion",
                        verbose_name="versão do template",
                    ),
                ),
                (
                    "group_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sector_rules",
                        to="templates_engine.validationgroupversion",
                        verbose_name="versão do grupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "setor de grupo",
                "verbose_name_plural": "setores de grupos",
                "db_table": "SGPD_VALIDATION_GROUP_SECTOR",
                "ordering": ("group_version_id", "display_order", "id"),
            },
        ),
        migrations.AddField(
            model_name="validationgroup",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="templates_engine.validationgroupversion",
                verbose_name="versão vigente",
            ),
        ),
        migrations.CreateModel(
            name="WorkflowConfigurationAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("TEMPLATE_CREATED", "Template criado"),
                            ("TPL_VERSION_CREATED", "Versão de template criada"),
                            ("TEMPLATE_PUBLISHED", "Template publicado"),
                            ("GROUP_CREATED", "Grupo criado"),
                            ("GROUP_VERSION_CREATED", "Versão de grupo criada"),
                            ("GROUP_PUBLISHED", "Grupo publicado"),
                        ],
                        max_length=30,
                        verbose_name="tipo do evento",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(max_length=30, verbose_name="tipo de entidade"),
                ),
                (
                    "entity_id",
                    models.PositiveIntegerField(verbose_name="ID da entidade"),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ocorrido em"),
                ),
                ("data", models.JSONField(default=dict, verbose_name="dados")),
                (
                    "correlation_id",
                    models.CharField(default="-", max_length=64, verbose_name="correlation ID"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_configuration_events_performed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ator",
                    ),
                ),
            ],
            options={
                "verbose_name": "evento de configuração do workflow",
                "verbose_name_plural": "eventos de configuração do workflow",
                "db_table": "SGPD_WORKFLOW_CONFIG_AUDIT",
                "ordering": ("-occurred_at", "-id"),
            },
        ),
        migrations.AddConstraint(
            model_name="checklisttemplateversion",
            constraint=models.UniqueConstraint(
                fields=("template", "version_number"), name="SGPD_UQ_TPL_VERSION"
            ),
        ),
        migrations.AddConstraint(
            model_name="checklisttemplateversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("version_number__gt", 0),
                    models.Q(
                        ("default_due_hours__isnull", True),
                        ("default_due_hours__gt", 0),
                        _connector="OR",
                    ),
                ),
                name="SGPD_CK_TPL_VER_VALUES",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklisttemplateversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("published_at__isnull", True),
                        ("published_by__isnull", True),
                        ("status", "DRAFT"),
                    ),
                    models.Q(
                        ("published_at__isnull", False),
                        ("published_by__isnull", False),
                        ("status__in", ("PUBLISHED", "RETIRED")),
                    ),
                    _connector="OR",
                ),
                name="SGPD_CK_TPL_VER_LIFE",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklisttemplateitem",
            constraint=models.UniqueConstraint(
                fields=("template_version", "code"), name="SGPD_UQ_TPL_ITEM_CODE"
            ),
        ),
        migrations.AddConstraint(
            model_name="checklisttemplateitem",
            constraint=models.UniqueConstraint(
                fields=("template_version", "display_order"),
                name="SGPD_UQ_TPL_ITEM_ORDER",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklisttemplateitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("code__isnull", False),
                    ("display_order__gt", 0),
                    ("question__isnull", False),
                    ("response_type__isnull", False),
                ),
                name="SGPD_CK_TPL_ITEM_REQ",
            ),
        ),
        migrations.AddIndex(
            model_name="checklisttemplate",
            index=models.Index(fields=["sector", "is_active"], name="SGPD_IX_TPL_SECTOR"),
        ),
        migrations.AddConstraint(
            model_name="checklisttemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("code__isnull", False), ("name__isnull", False), ("version__gt", 0)
                ),
                name="SGPD_CK_TPL_REQUIRED",
            ),
        ),
        migrations.AddConstraint(
            model_name="validationgroupversion",
            constraint=models.UniqueConstraint(
                fields=("group", "version_number"), name="SGPD_UQ_GROUP_VERSION"
            ),
        ),
        migrations.AddConstraint(
            model_name="validationgroupversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("version_number__gt", 0)),
                name="SGPD_CK_GROUP_VER_NUM",
            ),
        ),
        migrations.AddConstraint(
            model_name="validationgroupversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("published_at__isnull", True),
                        ("published_by__isnull", True),
                        ("status", "DRAFT"),
                    ),
                    models.Q(
                        ("published_at__isnull", False),
                        ("published_by__isnull", False),
                        ("status__in", ("PUBLISHED", "RETIRED")),
                    ),
                    _connector="OR",
                ),
                name="SGPD_CK_GROUP_VER_LIFE",
            ),
        ),
        migrations.AddConstraint(
            model_name="validationgroupsector",
            constraint=models.UniqueConstraint(
                fields=("group_version", "sector"), name="SGPD_UQ_GROUP_SECTOR"
            ),
        ),
        migrations.AddConstraint(
            model_name="validationgroupsector",
            constraint=models.UniqueConstraint(
                fields=("group_version", "display_order"), name="SGPD_UQ_GROUP_ORDER"
            ),
        ),
        migrations.AddConstraint(
            model_name="validationgroupsector",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("display_order__gt", 0),
                    models.Q(
                        ("due_hours_override__isnull", True),
                        ("due_hours_override__gt", 0),
                        _connector="OR",
                    ),
                ),
                name="SGPD_CK_GROUP_SECTOR_VAL",
            ),
        ),
        migrations.AddConstraint(
            model_name="validationgroup",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("code__isnull", False), ("name__isnull", False), ("version__gt", 0)
                ),
                name="SGPD_CK_GROUP_REQUIRED",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowconfigurationauditevent",
            index=models.Index(
                fields=["entity_type", "entity_id", "occurred_at"],
                name="SGPD_IX_WF_CFG_ENTITY",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowconfigurationauditevent",
            index=models.Index(fields=["correlation_id"], name="SGPD_IX_WF_CFG_CORR"),
        ),
        migrations.AddConstraint(
            model_name="workflowconfigurationauditevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("actor__isnull", False),
                    ("correlation_id__isnull", False),
                    ("entity_id__gt", 0),
                    ("entity_type__isnull", False),
                    ("event_type__isnull", False),
                ),
                name="SGPD_CK_WF_CFG_AUDIT_REQ",
            ),
        ),
    ]
