# Generated by Django 5.2.16 on 2026-07-30 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates_engine", "0005_add_group_draft_updated_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowconfigurationauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("TEMPLATE_CREATED", "Template criado"),
                    ("TPL_VERSION_CREATED", "Versão de template criada"),
                    ("TPL_DRAFT_UPDATED", "Rascunho de template alterado"),
                    ("TEMPLATE_PUBLISHED", "Template publicado"),
                    ("GROUP_CREATED", "Grupo criado"),
                    ("GROUP_VERSION_CREATED", "Versão de grupo criada"),
                    ("GROUP_DRAFT_UPDATED", "Rascunho de grupo alterado"),
                    ("GROUP_PUBLISHED", "Grupo publicado"),
                    ("APPLICAB_RULE_CREATED", "Regra de aplicabilidade criada"),
                    ("APPLICAB_RULE_UPDATED", "Regra de aplicabilidade alterada"),
                ],
                max_length=30,
                verbose_name="tipo do evento",
            ),
        ),
        migrations.CreateModel(
            name="GroupApplicabilityRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nome")),
                (
                    "priority",
                    models.PositiveIntegerField(default=100, verbose_name="prioridade"),
                ),
                (
                    "company_code",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="código da empresa"
                    ),
                ),
                (
                    "branch_code",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="código da filial"
                    ),
                ),
                (
                    "employee_type_code",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="tipo de colaborador"
                    ),
                ),
                (
                    "job_structure_code",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="estrutura de cargos"
                    ),
                ),
                (
                    "job_code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="código do cargo",
                    ),
                ),
                (
                    "cost_center_code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="código do centro de custo",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativa")),
                (
                    "valid_from",
                    models.DateField(blank=True, null=True, verbose_name="válida de"),
                ),
                (
                    "valid_to",
                    models.DateField(blank=True, null=True, verbose_name="válida até"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criada em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizada em"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="versão de concorrência"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applicability_rules",
                        to="templates_engine.validationgroup",
                        verbose_name="grupo sugerido",
                    ),
                ),
            ],
            options={
                "verbose_name": "regra de aplicabilidade",
                "verbose_name_plural": "regras de aplicabilidade",
                "db_table": "SGPD_GROUP_APPLICAB_RULE",
                "ordering": ("-priority", "name", "pk"),
                "indexes": [
                    models.Index(
                        fields=["is_active", "company_code", "branch_code"],
                        name="SGPD_IX_APPLICAB_RULE_HIT",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("name__isnull", False),
                            ("priority__gt", 0),
                            ("version__gt", 0),
                        ),
                        name="SGPD_CK_APPLICAB_RULE_REQ",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("valid_from__isnull", True),
                            ("valid_to__isnull", True),
                            ("valid_to__gte", models.F("valid_from")),
                            _connector="OR",
                        ),
                        name="SGPD_CK_APPLICAB_RULE_WIN",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("branch_code__isnull", True),
                            ("company_code__isnull", False),
                            _connector="OR",
                        ),
                        name="SGPD_CK_APPLICAB_RULE_BRA",
                    ),
                ],
            },
        ),
    ]
