# Generated by Django 5.2.16 on 2026-07-31 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates_engine", "0006_add_group_applicability_rules"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowconfigurationauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("TEMPLATE_CREATED", "Template criado"),
                    ("TPL_VERSION_CREATED", "Versão de template criada"),
                    ("TPL_DRAFT_UPDATED", "Rascunho de template alterado"),
                    ("TPL_DRAFT_DELETED", "Rascunho de template excluído"),
                    ("TEMPLATE_PUBLISHED", "Template publicado"),
                    ("GROUP_CREATED", "Grupo criado"),
                    ("GROUP_VERSION_CREATED", "Versão de grupo criada"),
                    ("GROUP_DRAFT_UPDATED", "Rascunho de grupo alterado"),
                    ("GROUP_DRAFT_DELETED", "Rascunho de grupo excluído"),
                    ("GROUP_PUBLISHED", "Grupo publicado"),
                    ("APPLICAB_RULE_CREATED", "Regra de aplicabilidade criada"),
                    ("APPLICAB_RULE_UPDATED", "Regra de aplicabilidade alterada"),
                ],
                max_length=30,
                verbose_name="tipo do evento",
            ),
        ),
    ]
