"""Transactional use cases for the offboarding workflow."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date, datetime

from django.core.exceptions import PermissionDenied, ValidationError
from django.db import IntegrityError, transaction
from django.utils import timezone

from apps.accounts.authorization import has_effective_role
from apps.accounts.models import (
    PEOPLE_DEPARTMENT_ROLE_CODE,
    RoleAssignment,
    User,
)
from apps.integrations.senior.dto import EmployeeDetail
from apps.integrations.senior.exceptions import SeniorContractError
from apps.integrations.senior.repository import SeniorRepository
from config.middleware import correlation_id

from .models import (
    EmployeeSnapshot,
    OffboardingProcess,
    ProcessAuditEvent,
    ProcessEventType,
    ProcessStatus,
)

PROCESS_OPENED_DESCRIPTION = "Abertura explícita de processo demissional pelo DP."


def _require_people_department_role(
    actor: User,
    *,
    company_code: int,
    branch_code: int,
) -> None:
    if not has_effective_role(
        actor,
        PEOPLE_DEPARTMENT_ROLE_CODE,
        company_code=company_code,
        branch_code=branch_code,
    ):
        raise PermissionDenied(
            "O ator não possui o papel DP vigente para a empresa e a filial informadas."
        )


def _required_text(value: str, field: str, message: str) -> str:
    normalized = value.strip()
    if not normalized:
        raise ValidationError({field: message})
    return normalized


def _employee_key(
    company_code: int,
    branch_code: int,
    employee_type_code: int,
    registration: int,
) -> str:
    return f"{company_code}:{branch_code}:{employee_type_code}:{registration}"


def _aware_datetime(value: datetime | None) -> datetime | None:
    if value is None or timezone.is_aware(value):
        return value
    return timezone.make_aware(value)


def _validate_employee_identity(
    employee: EmployeeDetail,
    *,
    company_code: int,
    branch_code: int,
    employee_type_code: int,
    registration: int,
) -> None:
    returned_key = (
        employee.company,
        employee.branch,
        employee.employee_type,
        employee.registration,
    )
    expected_key = (company_code, branch_code, employee_type_code, registration)
    if returned_key != expected_key:
        raise SeniorContractError("O Senior retornou uma chave de colaborador divergente.")


def _lock_users(actor: User, manager_user_id: int) -> tuple[User, User]:
    user_ids = sorted({actor.pk, manager_user_id})
    users = {
        user.pk: user
        for user in User.objects.select_for_update().filter(pk__in=user_ids).order_by("pk")
    }
    try:
        locked_actor = users[actor.pk]
    except KeyError as exc:
        raise PermissionDenied("O ator não está mais disponível.") from exc
    try:
        manager = users[manager_user_id]
    except KeyError as exc:
        raise ValidationError(
            {"manager_user_id": "O gestor selecionado não existe no SGPD."}
        ) from exc
    return locked_actor, manager


def _lock_people_department_assignments(actor: User) -> None:
    # Materialize without slicing: Oracle cannot combine FOR UPDATE with the
    # row limiting generated by first()/exists().
    list(
        RoleAssignment.objects.select_for_update()
        .filter(user=actor, role__code=PEOPLE_DEPARTMENT_ROLE_CODE)
        .order_by("pk")
    )


def _manager_snapshot(manager: User) -> tuple[str, str]:
    if not manager.is_active:
        raise ValidationError({"manager_user_id": "O gestor selecionado está inativo."})
    name = manager.get_full_name().strip()
    email = manager.email.strip().lower()
    if not name:
        raise ValidationError(
            {"manager_user_id": "O gestor precisa possuir nome completo cadastrado."}
        )
    if not email:
        raise ValidationError({"manager_user_id": "O gestor precisa possuir e-mail cadastrado."})
    return name, email


@dataclass(frozen=True, slots=True)
class OpenOffboardingProcessCommand:
    actor: User
    company_code: int
    branch_code: int
    employee_type_code: int
    employee_registration: int
    manager_user_id: int
    planned_termination_date: date
    due_date: date
    reason: str
    priority: str
    notes: str = ""


class OpenOffboardingProcessService:
    def __init__(self, *, repository: SeniorRepository | None = None) -> None:
        self._repository = repository or SeniorRepository()

    def execute(self, command: OpenOffboardingProcessCommand) -> OffboardingProcess:
        reason = _required_text(command.reason, "reason", "O motivo é obrigatório.")
        priority = _required_text(
            command.priority,
            "priority",
            "A prioridade é obrigatória.",
        )
        notes = command.notes.strip()

        # Fail before consulting personal data when the actor has no functional
        # authority. The same check is repeated after locking inside the write
        # transaction so revocation and opening have a deterministic winner.
        _require_people_department_role(
            command.actor,
            company_code=command.company_code,
            branch_code=command.branch_code,
        )
        if not User.objects.filter(pk=command.manager_user_id, is_active=True).exists():
            raise ValidationError(
                {"manager_user_id": "Selecione um gestor ativo cadastrado no SGPD."}
            )

        employee = self._repository.get_employee(
            company=command.company_code,
            branch=command.branch_code,
            employee_type=command.employee_type_code,
            registration=command.employee_registration,
        )
        if employee is None:
            raise ValidationError(
                {
                    "employee_registration": (
                        "O colaborador não existe ou deixou de ser elegível no Senior HCM."
                    )
                }
            )
        _validate_employee_identity(
            employee,
            company_code=command.company_code,
            branch_code=command.branch_code,
            employee_type_code=command.employee_type_code,
            registration=command.employee_registration,
        )
        source_queried_at = timezone.now()

        with transaction.atomic():
            actor, manager = _lock_users(command.actor, command.manager_user_id)
            _lock_people_department_assignments(actor)
            _require_people_department_role(
                actor,
                company_code=command.company_code,
                branch_code=command.branch_code,
            )
            manager_name, manager_email = _manager_snapshot(manager)

            active_employee_key = _employee_key(
                command.company_code,
                command.branch_code,
                command.employee_type_code,
                command.employee_registration,
            )
            existing = list(
                OffboardingProcess.objects.select_for_update()
                .filter(active_employee_key=active_employee_key)
                .order_by("pk")
            )
            if existing:
                raise ValidationError(
                    {
                        "employee_registration": (
                            "Já existe um processo não encerrado para este colaborador."
                        )
                    }
                )

            process = OffboardingProcess(
                status=ProcessStatus.DRAFT,
                company_code=command.company_code,
                branch_code=command.branch_code,
                employee_type_code=command.employee_type_code,
                employee_registration=command.employee_registration,
                active_employee_key=active_employee_key,
                manager=manager,
                manager_name_snapshot=manager_name,
                manager_email_snapshot=manager_email,
                opened_by=actor,
                planned_termination_date=command.planned_termination_date,
                due_date=command.due_date,
                reason=reason,
                priority=priority,
                notes=notes,
            )
            process.full_clean(exclude={"active_employee_key"})
            try:
                process.save()
            except IntegrityError as exc:
                raise ValidationError(
                    {
                        "employee_registration": (
                            "Já existe um processo não encerrado para este colaborador."
                        )
                    }
                ) from exc

            snapshot = EmployeeSnapshot(
                process=process,
                company_code=employee.company,
                branch_code=employee.branch,
                branch_legal_name=employee.legal_name,
                employee_type_code=employee.employee_type,
                employee_type_description=employee.employee_type_description,
                registration=employee.registration,
                employee_name=employee.name,
                masked_cpf=employee.masked_cpf,
                admission_date=employee.admission_date.date(),
                leave_code=employee.leave_code,
                leave_description=employee.leave_description,
                leave_date=employee.leave_date.date() if employee.leave_date else None,
                job_structure_code=employee.job_structure,
                job_code=employee.job_code,
                job_description=employee.job_description,
                cost_center_code=employee.cost_center,
                cost_center_description=employee.cost_center_description,
                source_updated_at=_aware_datetime(employee.source_updated_at),
                source_queried_at=source_queried_at,
            )
            snapshot.full_clean()
            snapshot.save()

            ProcessAuditEvent.objects.create(
                process=process,
                event_type=ProcessEventType.OPENED,
                actor=actor,
                description=PROCESS_OPENED_DESCRIPTION,
                data={
                    "status": ProcessStatus.DRAFT,
                    "company_code": command.company_code,
                    "branch_code": command.branch_code,
                    "employee_type_code": command.employee_type_code,
                    "employee_registration": command.employee_registration,
                    "manager_user_id": manager.pk,
                    "planned_termination_date": command.planned_termination_date.isoformat(),
                    "due_date": command.due_date.isoformat(),
                    "priority": priority,
                },
                correlation_id=correlation_id.get(),
            )
            return process
