# Generated by Django 5.2.16 on 2026-07-31 16:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("offboarding", "0007_alter_processauditevent_event_type"),
        ("sectors", "0004_use_automatic_sector_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("TAREFA_A_VENCER", "Tarefa a vencer"),
                            ("TAREFA_VENCE_EM_BREVE", "Tarefa próxima do vencimento"),
                            ("TAREFA_VENCIDA", "Tarefa vencida"),
                            (
                                "TAREFA_VENCIDA_CRITICA",
                                "Tarefa vencida em nível crítico",
                            ),
                            ("PROCESSO_PROXIMO_LIMITE", "Processo próximo do limite"),
                            ("TAREFA_ATRIBUIDA", "Tarefa atribuída ao setor"),
                            ("PENDENCIA_BLOQUEANTE", "Pendência bloqueante registrada"),
                            ("VALOR_AGUARDA_DECISAO", "Valor aguardando decisão"),
                            ("VALOR_DECIDIDO", "Valor decidido"),
                        ],
                        max_length=30,
                        verbose_name="evento",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("EMAIL", "E-mail")],
                        default="EMAIL",
                        max_length=20,
                        verbose_name="canal",
                    ),
                ),
                (
                    "dedup_key",
                    models.CharField(max_length=120, verbose_name="chave de deduplicação"),
                ),
                (
                    "recipient_email",
                    models.EmailField(max_length=254, verbose_name="endereço do destinatário"),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="assunto")),
                ("body", models.TextField(verbose_name="corpo")),
                (
                    "context",
                    models.JSONField(blank=True, default=dict, verbose_name="contexto técnico"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("ENVIANDO", "Em envio"),
                            ("ENVIADA", "Enviada"),
                            ("FALHA", "Falha"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                        verbose_name="situação",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(default=0, verbose_name="tentativas"),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(default=5, verbose_name="tentativas máximas"),
                ),
                (
                    "next_attempt_at",
                    models.DateTimeField(verbose_name="próxima tentativa em"),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, verbose_name="último erro"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criada em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizada em"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="enviada em"),
                ),
                (
                    "correlation_id",
                    models.CharField(blank=True, max_length=64, verbose_name="correlation ID"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="versão de concorrência"),
                ),
                (
                    "process",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="offboarding.offboardingprocess",
                        verbose_name="processo",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="destinatário",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="sectors.validationsector",
                        verbose_name="setor",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="offboarding.processsectortask",
                        verbose_name="tarefa",
                    ),
                ),
            ],
            options={
                "verbose_name": "notificação",
                "verbose_name_plural": "notificações",
                "db_table": "SGPD_NOTIFICATION",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="NotificationAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(verbose_name="número da tentativa"),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="iniciada em"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="finalizada em"),
                ),
                (
                    "succeeded",
                    models.BooleanField(blank=True, null=True, verbose_name="bem-sucedida"),
                ),
                ("error", models.TextField(blank=True, verbose_name="erro")),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_attempts",
                        to="notifications.notification",
                        verbose_name="notificação",
                    ),
                ),
            ],
            options={
                "verbose_name": "tentativa de entrega",
                "verbose_name_plural": "tentativas de entrega",
                "db_table": "SGPD_NOTIFICATION_ATTEMPT",
                "ordering": ("notification_id", "attempt_number"),
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["status", "next_attempt_at"], name="SGPD_IX_NOTIF_DISPATCH"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["process", "status"], name="SGPD_IX_NOTIF_PROCESS"),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(fields=("dedup_key",), name="SGPD_UQ_NOTIF_DEDUP"),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_attempts__gt", 0), ("version__gt", 0)),
                name="SGPD_CK_NOTIF_VALUES",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("sent_at__isnull", False), ("status", "ENVIADA")),
                    models.Q(
                        models.Q(("status", "ENVIADA"), _negated=True),
                        ("sent_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="SGPD_CK_NOTIF_SENT_AT",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationattempt",
            constraint=models.UniqueConstraint(
                fields=("notification", "attempt_number"), name="SGPD_UQ_NOTIF_ATTEMPT"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_number__gt", 0)),
                name="SGPD_CK_NOTIF_ATT_NUMBER",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("finished_at__isnull", True), ("succeeded__isnull", True)),
                    models.Q(("finished_at__isnull", False), ("succeeded__isnull", False)),
                    _connector="OR",
                ),
                name="SGPD_CK_NOTIF_ATT_CLOSED",
            ),
        ),
    ]
