# Generated by Django 5.2.16 on 2026-07-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="event",
            field=models.CharField(
                choices=[
                    ("TAREFA_A_VENCER", "Tarefa a vencer"),
                    ("TAREFA_VENCE_EM_BREVE", "Tarefa próxima do vencimento"),
                    ("TAREFA_VENCIDA", "Tarefa vencida"),
                    ("TAREFA_VENCIDA_CRITICA", "Tarefa vencida em nível crítico"),
                    ("PROCESSO_PROXIMO_LIMITE", "Processo próximo do limite"),
                    ("TAREFA_ATRIBUIDA", "Tarefa atribuída ao setor"),
                    ("PENDENCIA_BLOQUEANTE", "Pendência bloqueante registrada"),
                    ("VALOR_AGUARDA_DECISAO", "Valor aguardando decisão"),
                    ("VALOR_DECIDIDO", "Valor decidido"),
                    ("PROCESSO_CANCELADO", "Processo cancelado"),
                    ("PROCESSO_REABERTO", "Processo reaberto"),
                ],
                max_length=30,
                verbose_name="evento",
            ),
        ),
    ]
