# Generated by Django 5.2.16 on 2026-07-29 00:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidationSector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="código"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nome")),
                ("description", models.TextField(blank=True, verbose_name="descrição")),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "default_due_hours",
                    models.PositiveIntegerField(verbose_name="prazo padrão em horas"),
                ),
                (
                    "blocks_process",
                    models.BooleanField(default=True, verbose_name="bloqueia o processo"),
                ),
                (
                    "allows_amount",
                    models.BooleanField(default=False, verbose_name="permite lançar valores"),
                ),
                (
                    "requires_evidence",
                    models.BooleanField(default=False, verbose_name="exige evidência"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="versão de concorrência"),
                ),
                (
                    "escalation_sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escalation_sources",
                        to="sectors.validationsector",
                        verbose_name="setor de escalada",
                    ),
                ),
            ],
            options={
                "verbose_name": "setor de validação",
                "verbose_name_plural": "setores de validação",
                "db_table": "SGPD_VALIDATION_SECTOR",
                "ordering": ("code",),
                "permissions": [("manage_sectors", "Pode criar e manter setores de validação")],
            },
        ),
        migrations.CreateModel(
            name="SectorScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("GLOBAL", "Global"),
                            ("COMPANY", "Empresa"),
                            ("BRANCH", "Filial"),
                        ],
                        max_length=10,
                        verbose_name="tipo de escopo",
                    ),
                ),
                (
                    "company_code",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="código da empresa"
                    ),
                ),
                (
                    "branch_code",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="código da filial"
                    ),
                ),
                (
                    "scope_key",
                    models.CharField(editable=False, max_length=64, verbose_name="chave do escopo"),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scopes",
                        to="sectors.validationsector",
                        verbose_name="setor",
                    ),
                ),
            ],
            options={
                "verbose_name": "escopo de setor",
                "verbose_name_plural": "escopos de setores",
                "db_table": "SGPD_SECTOR_SCOPE",
                "ordering": ("sector_id", "scope_key"),
            },
        ),
        migrations.CreateModel(
            name="SectorAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("SECTOR_CREATED", "Setor criado"),
                            ("SECTOR_UPDATED", "Setor atualizado"),
                            ("SECTOR_ACTIVATED", "Setor ativado"),
                            ("SECTOR_DEACTIVATED", "Setor inativado"),
                        ],
                        max_length=30,
                        verbose_name="tipo do evento",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ocorrido em"),
                ),
                ("reason", models.TextField(verbose_name="justificativa")),
                ("changes", models.JSONField(default=dict, verbose_name="alterações")),
                (
                    "correlation_id",
                    models.CharField(default="-", max_length=64, verbose_name="correlation ID"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sector_events_performed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ator",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="sectors.validationsector",
                        verbose_name="setor",
                    ),
                ),
            ],
            options={
                "verbose_name": "evento de auditoria de setor",
                "verbose_name_plural": "eventos de auditoria de setores",
                "db_table": "SGPD_SECTOR_AUDIT",
                "ordering": ("-occurred_at", "-id"),
            },
        ),
        migrations.AddIndex(
            model_name="validationsector",
            index=models.Index(fields=["is_active", "code"], name="SGPD_IX_SECTOR_ACTIVE"),
        ),
        migrations.AddConstraint(
            model_name="validationsector",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("code__isnull", False),
                    ("default_due_hours__gt", 0),
                    ("name__isnull", False),
                ),
                name="SGPD_CK_SECTOR_REQUIRED",
            ),
        ),
        migrations.AddConstraint(
            model_name="validationsector",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gt", 0)), name="SGPD_CK_SECTOR_VERSION"
            ),
        ),
        migrations.AddIndex(
            model_name="sectorscope",
            index=models.Index(fields=["company_code", "branch_code"], name="SGPD_IX_SECTOR_ORG"),
        ),
        migrations.AddConstraint(
            model_name="sectorscope",
            constraint=models.UniqueConstraint(
                fields=("sector", "scope_key"), name="SGPD_UQ_SECTOR_SCOPE"
            ),
        ),
        migrations.AddConstraint(
            model_name="sectorscope",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("branch_code__isnull", True),
                        ("company_code__isnull", True),
                        ("scope_type", "GLOBAL"),
                    ),
                    models.Q(
                        ("branch_code__isnull", True),
                        ("company_code__isnull", False),
                        ("scope_type", "COMPANY"),
                    ),
                    models.Q(
                        ("branch_code__isnull", False),
                        ("company_code__isnull", False),
                        ("scope_type", "BRANCH"),
                    ),
                    _connector="OR",
                ),
                name="SGPD_CK_SECTOR_SCOPE",
            ),
        ),
        migrations.AddConstraint(
            model_name="sectorscope",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("scope_key__isnull", False),
                    ("scope_type__isnull", False),
                ),
                name="SGPD_CK_SECTOR_SCOPE_REQ",
            ),
        ),
        migrations.AddConstraint(
            model_name="sectorscope",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("company_code__isnull", True),
                        ("company_code__gt", 0),
                        _connector="OR",
                    ),
                    models.Q(
                        ("branch_code__isnull", True),
                        ("branch_code__gt", 0),
                        _connector="OR",
                    ),
                ),
                name="SGPD_CK_SECTOR_CODES",
            ),
        ),
        migrations.AddIndex(
            model_name="sectorauditevent",
            index=models.Index(fields=["sector", "occurred_at"], name="SGPD_IX_SECTOR_AUDIT"),
        ),
        migrations.AddIndex(
            model_name="sectorauditevent",
            index=models.Index(fields=["correlation_id"], name="SGPD_IX_SECTOR_CORR"),
        ),
        migrations.AddConstraint(
            model_name="sectorauditevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("correlation_id__isnull", False),
                    ("event_type__isnull", False),
                    ("reason__isnull", False),
                ),
                name="SGPD_CK_SECTOR_AUDIT_REQ",
            ),
        ),
    ]
