# Generated by Django 5.2.16 on 2026-07-29 11:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sectors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectorauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("SECTOR_CREATED", "Setor criado"),
                    ("SECTOR_UPDATED", "Setor atualizado"),
                    ("SECTOR_ACTIVATED", "Setor ativado"),
                    ("SECTOR_DEACTIVATED", "Setor inativado"),
                    ("SECTOR_RESPONSIBLE_ASSIGNED", "Responsável associado"),
                    ("SECTOR_RESPONSIBLE_UPDATED", "Responsabilidade atualizada"),
                    ("SECTOR_RESPONSIBLE_REVOKED", "Responsabilidade revogada"),
                ],
                max_length=30,
                verbose_name="tipo do evento",
            ),
        ),
        migrations.CreateModel(
            name="SectorResponsible",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("GLOBAL", "Global"),
                            ("COMPANY", "Empresa"),
                            ("BRANCH", "Filial"),
                        ],
                        max_length=10,
                        verbose_name="tipo de escopo",
                    ),
                ),
                (
                    "company_code",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="código da empresa",
                    ),
                ),
                (
                    "branch_code",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="código da filial",
                    ),
                ),
                (
                    "scope_key",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        verbose_name="chave do escopo",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="válido desde",
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="válido até",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "assigned_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="atribuído em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="atualizado em",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="revogado em",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        verbose_name="versão de concorrência",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sector_responsibilities_assigned",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="atribuído por",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sector_responsibilities_revoked",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="revogado por",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responsibles",
                        to="sectors.validationsector",
                        verbose_name="setor",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sector_responsibilities_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="atualizado por",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sector_responsibilities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "responsável de setor",
                "verbose_name_plural": "responsáveis de setores",
                "db_table": "SGPD_SECTOR_RESPONSIBLE",
                "ordering": ("sector__code", "user__username", "scope_key"),
                "indexes": [
                    models.Index(
                        fields=["sector", "is_active", "valid_from"],
                        name="SGPD_IX_RESP_SECTOR",
                    ),
                    models.Index(
                        fields=["user", "is_active", "valid_from"],
                        name="SGPD_IX_RESP_USER",
                    ),
                    models.Index(
                        fields=["company_code", "branch_code", "is_active"],
                        name="SGPD_IX_RESP_ORG",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sector", "user", "scope_key"),
                        name="SGPD_UQ_SECTOR_RESP_SCOPE",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("branch_code__isnull", True),
                                ("company_code__isnull", True),
                                ("scope_type", "GLOBAL"),
                            ),
                            models.Q(
                                ("branch_code__isnull", True),
                                ("company_code__isnull", False),
                                ("scope_type", "COMPANY"),
                            ),
                            models.Q(
                                ("branch_code__isnull", False),
                                ("company_code__isnull", False),
                                ("scope_type", "BRANCH"),
                            ),
                            _connector="OR",
                        ),
                        name="SGPD_CK_SECTOR_RESP_SCOPE",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("valid_until__isnull", True),
                            ("valid_until__gt", models.F("valid_from")),
                            _connector="OR",
                        ),
                        name="SGPD_CK_SECTOR_RESP_VALID",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("is_active", True),
                                ("revoked_at__isnull", True),
                                ("revoked_by__isnull", True),
                            ),
                            models.Q(
                                ("is_active", False),
                                ("revoked_at__isnull", False),
                                ("revoked_by__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="SGPD_CK_SECTOR_RESP_REVOKE",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("assigned_by__isnull", False),
                            ("scope_key__isnull", False),
                            ("scope_type__isnull", False),
                            ("updated_by__isnull", False),
                        ),
                        name="SGPD_CK_SECTOR_RESP_REQ",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("company_code__isnull", True),
                                ("company_code__gt", 0),
                                _connector="OR",
                            ),
                            models.Q(
                                ("branch_code__isnull", True),
                                ("branch_code__gt", 0),
                                _connector="OR",
                            ),
                        ),
                        name="SGPD_CK_SECTOR_RESP_CODES",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gt", 0)),
                        name="SGPD_CK_SECTOR_RESP_VERSION",
                    ),
                ],
            },
        ),
    ]
